import React from "react";
import Button from "react-bootstrap/Button";
import firebase from "firebase/firebase.js";

let results = [
  ["Stephen Appert", "Accounting I", 1, 2008, 1],
  ["Gefflin Fu", "Accounting I", 1, 2008, 3],
  ["Eddson Alcid", "Accounting II", 1, 2008, 1],
  ["Stephen Appert", "Accounting II", 1, 2008, 5],
  [
    "Irene Baker",
    "Katrina Rogan",
    "Nadeeka Karunaratne",
    "American Enterprise",
    1,
    2008,
    4,
  ],
  [
    "Keri Omuro",
    "Sabrina Siu",
    "Jennifer Wang",
    "Banking and Financial Systems",
    1,
    2008,
    2,
  ],
  ["Laurie Sartain", "Business Calculations", 1, 2008, 2],
  ["Jonathan Lo", "Business Communication", 1, 2008, 2],
  ["Katrina Rogan", "Sushmita Shrikanth", "Business Ethics", 1, 2008, 4],
  [
    "Eddson Alcid",
    "Ana Martynova",
    "Laurie Sartain",
    "Business Financial Plan",
    1,
    2008,
    2,
  ],
  ["Amber Feng", "Business Law", 1, 2008, 1],
  ["Connie Chen", "Business Law", 1, 2008, 4],
  ["Nadeeka Karunaratne", "Business Law", 1, 2008, 2],
  ["Mattan Mansoor", "Business Law", 1, 2008, 5],
  ["Naddav Paran", "Business Law", 1, 2008, 7],
  ["Wendy Zhao", "Business Law", 1, 2008, 6],
  ["Jessica Li", "Business Math", 1, 2008, 6],
  [
    "Shawn Xu",
    "Saayeli Mukherji",
    "Spandana Pasan",
    "Business Plan",
    1,
    2008,
    1,
  ],
  [
    "Drew Haven",
    "Ashley Ott",
    "Katarina Plavec",
    "Business Presentation",
    1,
    2008,
    1,
  ],
  ["Matt Pak", "Computer Applications", 1, 2008, 9],
  ["Mehrdad Niknami", "Computer Problem Solving", 1, 2008, 4],
  ["Mark Orlovsky", "Computer Problem Solving", 1, 2008, 5],
  ["Magdalena Mardinian", "Creed Contest", 1, 2008, 1],
  [
    "Stacy Hwang",
    "Tram Hoang",
    "Mark Sagherian",
    "Community Service",
    1,
    2008,
    1,
  ],
  ["Jonathan Lo", "Cyber Security", 1, 2008, 3],
  ["Alan Guo", "Database Design and Application", 1, 2008, 5],
  ["Drew Haven", "Desktop Application Programming", 1, 2008, 3],
  ["Winston Hsu", "Desktop Application Programming", 1, 2008, 1],
  ["Mehrdad Niknami", "Desktop Application Programming", 1, 2008, 2],
  ["Ben Pool", "Eric Liu", "Digital Video Production", 1, 2008, 3],
  ["Anran Li", "Sangeeta Mondal", "Yi-An Tseng", "E-Business", 1, 2008, 2],
  ["Nima Rahnemoon", "Economics", 1, 2008, 9],
  ["Krzys Brozek", "Economics", 1, 2008, 2],
  [
    "Braden Holstege",
    "Robert Nishihara",
    "Bryce Wilson",
    "Emerging Business Issues",
    1,
    2008,
    1,
  ],
  [
    "Jim Danz",
    "Rohit Ramchandani",
    "Aria Srinivasan",
    "Entrepreneurship",
    1,
    2008,
    2,
  ],
  ["Shawn Xu", "Future Business Leader", 1, 2008, 5],
  ["Jim Danz", "Future Business Leader", 1, 2008, 1],
  [
    "Nikita Khetan",
    "Naddav Paran",
    "Hailun Ying",
    "Global Business",
    1,
    2008,
    1,
  ],
  ["Amber Feng", "Internet Application Programming", 1, 2008, 3],
  ["Anhang Zhu", "Internet Application Programming", 1, 2008, 2],
  ["Braden Holstege", "Introduction to Business", 1, 2008, 4],
  ["Alissa Song", "Introduction to Business", 1, 2008, 1],
  ["Kathy Sun", "Introduction to Business", 1, 2008, 7],
  ["Kevin Yang", "Introduction to Business", 1, 2008, 6],
  ["Mingja Edholm", "Introduction to Business Communication", 1, 2008, 6],
  ["Sophie Mou", "Introduction to Business Communication", 1, 2008, 8],
  ["Kenny Chow", "Introduction to Technology Concepts", 1, 2008, 6],
  ["Andres Gaeta", "Introduction to Technology Concepts", 1, 2008, 4],
  ["Benjamin Low", "Introduction to Technology Concepts", 1, 2008, 2],
  ["Joel Sheng", "Introduction to Technology Concepts", 1, 2008, 1],
  ["Danette Lee", "Job Interview", 1, 2008, 5],
  [
    "Max Babicz",
    "Evan Harris",
    "Alex Hsiung",
    "Management Decision Making",
    1,
    2008,
    1,
  ],
  ["Arnold Chu", "Marketing", 1, 2008, 2],
  ["Clara Lee", "Marketing", 1, 2008, 4],
  ["Rohit Ramchandani", "Marketing", 1, 2008, 1],
  ["Anhang Zhu", "Nima Rahnemoon", "Carson Tang", "Network Design", 1, 2008, 1],
  ["Anran Li", "Networking Concepts", 1, 2008, 10],
  ["Michael Kamradt", "Networking Concepts", 1, 2008, 8],
  [
    "Saayeli Mukherji",
    "Bryce Wilson",
    "Alissa Song",
    "Partnership with Business",
    1,
    2008,
    1,
  ],
  ["Howard Li", "Personal Finance", 1, 2008, 4],
  ["Keri Omuro", "Personal Finance", 1, 2008, 2],
  ["Alissa Song", "Public Speaking I", 1, 2008, 1],
  ["Dana Barzilay", "Public Speaking II", 1, 2008, 1],
  ["Justin Bettman", "Spreadsheet Applications", 1, 2008, 4],
  ["Winston Hsu", "Technology Concepts", 1, 2008, 1],
  ["Max Wallack", "Technology Concepts", 1, 2008, 3],
  ["Xin Wei", "Technology Concepts", 1, 2008, 2],
  ["Mark Orlovsky", "Technology Concepts", 1, 2008, 4],
  ["Xin Wei", "Max Wallack", "Desmond Lau", "Website Development", 1, 2008, 4],
  ["Jenny Shen", "Word Processing I", 1, 2008, 4],
  ["Wendy Zhao", "Word Processing I", 1, 2008, 9],
  ["Albert Wong", "Word Processing II", 1, 2008, 5],
  ["Chun-Hung Lin", "Accounting I", 0, 2008, 10],
  ["Gefflin Fu", "Accounting I", 0, 2008, 5],
  ["Jennifer Wang", "Accounting I", 0, 2008, 6],
  ["Keren Broyde", "Accounting I", 0, 2008, 9],
  ["Stephen Appert", "Accounting I", 0, 2008, 3],
  ["Chun-Hung Lin", "Accounting II", 0, 2008, 6],
  ["Eddson Alcid", "Accounting II", 0, 2008, 3],
  ["Erik Nelsen", "Accounting II", 0, 2008, 7],
  ["Keren Broyde", "Accounting II", 0, 2008, 10],
  ["Stephen Appert", "Accounting II", 0, 2008, 1],
  ["Albert Wong", "Business Calculations", 0, 2008, 10],
  ["Haoyuan (Howard) Li", "Business Calculations", 0, 2008, 5],
  ["Laurie Sartain", "Business Calculations", 0, 2008, 2],
  ["Jessica Yuan", "Business Communication", 0, 2008, 2],
  ["Jonathan Lo", "Business Communication", 0, 2008, 5],
  ["Ritu Kiragi", "Business Communication", 0, 2008, 6],
  ["Amber Feng", "Business Law", 0, 2008, 3],
  ["Connie Chen", "Business Law", 0, 2008, 5],
  ["Mattan Mansoor", "Business Law", 0, 2008, 4],
  ["Naddav Paran", "Business Law", 0, 2008, 2],
  ["Nadeeka Karunaratne", "Business Law", 0, 2008, 1],
  ["Wendy Zhao", "Business Law", 0, 2008, 6],
  ["Edwin Liao", "Business Math", 0, 2008, 4],
  ["Jessica Li", "Business Math", 0, 2008, 6],
  ["Annie Song", "Business Procedures", 0, 2008, 6],
  ["Jennifer Koh", "Business Procedures", 0, 2008, 10],
  ["Jessica Yi", "Business Procedures", 0, 2008, 9],
  ["Nancy Yi", "Business Procedures", 0, 2008, 1],
  ["Stephanie Zau", "Business Procedures", 0, 2008, 7],
  ["Kristina Mardinian", "Computer Applications", 0, 2008, 4],
  ["Kritica Joshi", "Computer Applications", 0, 2008, 6],
  ["Matt Pak", "Computer Applications", 0, 2008, 2],
  ["Andres Gaeta", "Computer Problem Solving", 0, 2008, 7],
  ["Eric Liu", "Computer Problem Solving", 0, 2008, 8],
  ["Jonathan Ou-Young", "Computer Problem Solving", 0, 2008, 9],
  ["Mark Orlovsky", "Computer Problem Solving", 0, 2008, 6],
  ["Mehrdad Niknami", "Computer Problem Solving", 0, 2008, 1],
  ["Gal Daskal", "Creed", 0, 2008, 7],
  ["Magdalena Mardinian", "Creed", 0, 2008, 1],
  ["Joel Sheng", "Cyber Security", 0, 2008, 3],
  ["Jonathan Lo", "Cyber Security", 0, 2008, 1],
  ["Kenny Chow", "Cyber Security", 0, 2008, 6],
  ["Zack Haven", "Cyber Security", 0, 2008, 8],
  ["Stanley Szeto", "Database Design and Application", 0, 2008, 8],
  ["Peter Tseng", "Database Design and Application", 0, 2008, 6],
  ["Alan Guo", "Database Design and Application", 0, 2008, 2],
  ["Krzysztof Brozek", "Economics", 0, 2008, 5],
  ["Nima Rahnemoon", "Economics", 0, 2008, 9],
  [
    "Jim Danz",
    "Rohit Ramchandani",
    "Aria Srinivasan",
    "Entrepreneurship",
    0,
    2008,
    1,
  ],
  ["Gal Daskal", "FBLA Principles and Procedures", 0, 2008, 7],
  ["Jenny Wang", "FBLA Principles and Procedures", 0, 2008, 4],
  ["Michael (Mingke) Li", "FBLA Principles and Procedures", 0, 2008, 9],
  ["Sonia Koroleva", "FBLA Principles and Procedures", 0, 2008, 5],
  ["Jim Danz", "Future Business Leader", 0, 2008, 1],
  ["Shawn Xu", "Future Business Leader", 0, 2008, 3],
  [
    "Nikita Khetan",
    "Naddav Paran",
    "Hailun Ying",
    "Global Business",
    0,
    2008,
    1,
  ],
  ["Alissa Song", "Introduction to Business", 0, 2008, 3],
  ["Braden Holstege", "Introduction to Business", 0, 2008, 6],
  ["Kathy Sun", "Introduction to Business", 0, 2008, 2],
  ["Kexin Yang", "Introduction to Business", 0, 2008, 5],
  ["Michael Kung", "Introduction to Business", 0, 2008, 8],
  ["Mingja Edholm", "Introduction to Business Communication", 0, 2008, 2],
  ["Sophie Mou", "Introduction to Business Communication", 0, 2008, 1],
  ["Andres Gaeta", "Introduction to Technology Concepts", 0, 2008, 1],
  ["Benjamin Low", "Introduction to Technology Concepts", 0, 2008, 3],
  ["Joel Sheng", "Introduction to Technology Concepts", 0, 2008, 2],
  ["Kenny Chow", "Introduction to Technology Concepts", 0, 2008, 4],
  ["Sotaro Sugimoto", "Introduction to Technology Concepts", 0, 2008, 7],
  ["Danette Lee", "Job Interview", 0, 2008, 2],
  ["Sriya Malladi", "Job Interview", 0, 2008, 6],
  [
    "Alex Hsiung",
    "Max Babicz",
    "Evan Harris",
    "Management Decision Making",
    0,
    2008,
    2,
  ],
  ["Arnold Chu", "Marketing", 0, 2008, 1],
  ["Clara Lee", "Marketing", 0, 2008, 7],
  ["Max Babicz", "Marketing", 0, 2008, 9],
  ["Rohit Ramchandani", "Marketing", 0, 2008, 2],
  ["Haoyuan (Howard) Li", "Personal Finance", 0, 2008, 5],
  ["Kerilyn (Keri) Omuro", "Personal Finance", 0, 2008, 1],
  ["Sabrina Siu", "Personal Finance", 0, 2008, 8],
  ["Alissa Song", "Public Speaking I", 0, 2008, 1],
  ["Dana Barzilay", "Public Speaking II", 0, 2008, 2],
  ["Bhargavi Chitneni", "Spreadsheet Applications", 0, 2008, 9],
  ["Justin Bettman", "Spreadsheet Applications", 0, 2008, 5],
  ["Yi-An Tseng", "Spreadsheet Applications", 0, 2008, 6],
  ["Mark Orlovsky", "Technology Concepts", 0, 2008, 3],
  ["Mattan Mansoor", "Technology Concepts", 0, 2008, 9],
  ["Max Wallack", "Technology Concepts", 0, 2008, 2],
  ["Winston Hsu", "Technology Concepts", 0, 2008, 1],
  ["Xin Wei", "Technology Concepts", 0, 2008, 6],
  ["Jenny Shen", "Word Processing I", 0, 2008, 4],
  ["Wendy Zhao", "Word Processing I", 0, 2008, 3],
  ["Albert Wong", "Word Processing II", 0, 2008, 3],
  ["Kendall Dea", "Word Processing II", 0, 2008, 6],
  ["Mark Sagherian", "Word Processing II", 0, 2008, 1],
  [
    "Jennifer Garnett",
    "Carson Tang",
    "Claire Brubaker",
    "American Enterprise",
    2,
    2007,
    3,
  ],
  ["Howard Li", "Banking and Financial Systems", 2, 2007, 3],
  ["Keri Omuro", "Banking and Financial Systems", 2, 2007, 5],
  [
    "Jennifer Garnett",
    "Claire Brubaker",
    "Eddson Alcid",
    "Business Financial Plan",
    2,
    2007,
    1,
  ],
  ["Jessica Yuan", "Business Law", 2, 2007, 2],
  ["Laurie Sartain", "Business Math", 2, 2007, 2],
  ["Drew Haven", "C++ Programming", 2, 2007, 4],
  ["John Chen", "Cyber Security", 2, 2007, 9],
  ["Charles Liu", "Jim Danz", "Sunny Chu", "Entrepreneurship", 2, 2007, 2],
  ["Aria Srinivasan", "Yifan Li", "Global Business", 2, 2007, 1],
  ["Bryce Wilson", "Introduction to Business", 2, 2007, 5],
  ["Max Babicz", "Introduction to Business", 2, 2007, 1],
  ["Stacy Hwang", "Introduction to Business", 2, 2007, 3],
  ["Mark Orlovsky", "Introduction to Technology Concepts", 2, 2007, 1],
  ["Max Wallack", "Introduction to Technology Concepts", 2, 2007, 9],
  ["Winston Hsu", "Introduction to Technology Concepts", 2, 2007, 6],
  [
    "Rohit Ramchandani",
    "Evan Harris",
    "Ashley Ott",
    "Management Decision Making",
    2,
    2007,
    1,
  ],
  ["Brandon Lee", "Marketing", 2, 2007, 5],
  ["Emma Tolley", "Oishee Bose", "Multimedia Presentation", 2, 2007, 3],
  [
    "Shawn Xu",
    "Amber Feng",
    "Aria Srinivasan",
    "Partnership with Business",
    2,
    2007,
    4,
  ],
  [
    "Anhang Zhu",
    "Carson Tang",
    "Nima Rahnemoon",
    "Website Development",
    2,
    2007,
    5,
  ],
  ["James Shieh", "Accounting I", 1, 2007, 4],
  ["Ning-Ning Ding", "Accounting I", 1, 2007, 1],
  ["Bob Zhao", "Accounting II", 1, 2007, 4],
  ["Claire Brubaker", "Accounting II", 1, 2007, 1],
  ["Connie Chen", "Accounting II", 1, 2007, 8],
  ["Jennifer Garnett", "Accounting II", 1, 2007, 6],
  [
    "Jennifer Garnett",
    "Carson Tang",
    "Claire Brubaker",
    "American Enterprise",
    1,
    2007,
    2,
  ],
  ["Howard Li", "Banking and Financial Systems", 1, 2007, 2],
  ["Keri Omuro", "Banking and Financial Systems", 1, 2007, 1],
  [
    "Wendy Huang",
    "Nikita Khetan",
    "Edward Wang",
    "Business Ethics",
    1,
    2007,
    2,
  ],
  [
    "Claire Brubaker",
    "Jennifer Garnett",
    "Eddson Alcid",
    "Business Financial Plan",
    1,
    2007,
    2,
  ],
  ["Eddson Alcid", "Business Law", 1, 2007, 4],
  ["Elaine Mao", "Business Law", 1, 2007, 2],
  ["Jessica Yuan", "Business Law", 1, 2007, 1],
  ["Jim Danz", "Business Law", 1, 2007, 5],
  ["Rohit Ramchandani", "Business Law", 1, 2007, 3],
  ["Spandana Pasam", "Business Law", 1, 2007, 6],
  ["Laurie Sartain", "Business Math", 1, 2007, 3],
  ["Amber Feng", "Ana Martynova", "Shawn Xu", "Business Plan", 1, 2007, 1],
  ["Iris Lin", "Business Procedures", 1, 2007, 1],
  ["Drew Haven", "C++ Programming", 1, 2007, 1],
  ["Marcos Gaeta", "C++ Programming", 1, 2007, 2],
  ["Stanley Szeto", "C++ Programming", 1, 2007, 4],
  [
    "Rohit Ramchandani",
    "Max Babicz",
    "Sunny Chu",
    "Community Service",
    1,
    2007,
    2,
  ],
  ["John Chen", "Cyber Security", 1, 2007, 4],
  ["Nitish Aitharaju", "Cyber Security", 1, 2007, 7],
  ["Robert Fischer", "Cyber Security", 1, 2007, 3],
  ["Sheng Lu", "Cyber Security", 1, 2007, 1],
  ["Eric Pai", "Iris Lin", "Desktop Publishing", 1, 2007, 1],
  ["Ben Pool", "Robert Fischer", "Digital Video Production", 1, 2007, 3],
  ["Andres Gaeta", "Greg Zumsteg", "E-Business", 1, 2007, 1],
  ["Emma Tolley", "Electronic Career Portfolio", 1, 2007, 1],
  ["Annie Stoner", "Stephanie Wong", "Emerging Business Issues", 1, 2007, 2],
  ["Jim Danz", "Sunny Chu", "Charles Liu", "Entrepreneurship", 1, 2007, 1],
  ["Ashley Ott", "FBLA Principles and Procedures", 1, 2007, 6],
  ["Brenda Hwang", "Future Business Leader", 1, 2007, 2],
  ["Aria Srinivasan", "Yifan Li", "Global Business", 1, 2007, 1],
  ["Katrina Rogan", "Impromptu Speaking", 1, 2007, 5],
  ["Bryce Wilson", "Introduction to Business", 1, 2007, 3],
  ["Max Babicz", "Introduction to Business", 1, 2007, 1],
  ["Stacy Hwang", "Introduction to Business", 1, 2007, 2],
  ["Irene Baker", "Introduction to Parliamentary Procedure", 1, 2007, 2],
  ["Mark Orlovsky", "Introduction to Technology Concepts", 1, 2007, 2],
  ["Max Wallack", "Introduction to Technology Concepts", 1, 2007, 3],
  ["Winston Hsu", "Introduction to Technology Concepts", 1, 2007, 1],
  ["Xin Wei", "Introduction to Technology Concepts", 1, 2007, 4],
  ["Aaron Wong", "Java Programming", 1, 2007, 2],
  ["Marcos Gaeta", "Java Programming", 1, 2007, 4],
  ["Winston Hsu", "Java Programming", 1, 2007, 3],
  [
    "Emma Tolley",
    "Charles Liu",
    "Jim Danz",
    "Local Chapter Annual Business Report",
    1,
    2007,
    4,
  ],
  [
    "Ashley Ott",
    "Evan Harris",
    "Rohit Ramchandani",
    "Management Decision Making",
    1,
    2007,
    1,
  ],
  ["Annie Stoner", "Marketing", 1, 2007, 6],
  ["Brandon Lee", "Marketing", 1, 2007, 4],
  ["Charles Liu", "Marketing", 1, 2007, 1],
  [
    "Emma Tolley",
    "Mary Plavec",
    "Oishee Bose",
    "Multimedia Presentation",
    1,
    2007,
    1,
  ],
  [
    "Nitish Aitharaju",
    "Anant Gupta",
    "Kevin Zhang",
    "Network Design",
    1,
    2007,
    1,
  ],
  ["Sicheng Liu", "Networking Concepts", 1, 2007, 2],
  ["Yi-An Tseng", "Networking Concepts", 1, 2007, 6],
  [
    "Shawn Xu",
    "Amber Feng",
    "Aria Srinivasan",
    "Partnership with Business",
    1,
    2007,
    1,
  ],
  ["Saayeli Mukherji", "Public Speaking I", 1, 2007, 5],
  ["Justin Bettman", "Spreadsheet Applications", 1, 2007, 10],
  ["Homestead", "Sweepstakes", 1, 2007, 1],
  ["Aaron Wong", "Technology Concepts", 1, 2007, 4],
  ["Anhang Zhu", "Technology Concepts", 1, 2007, 3],
  ["Drew Haven", "Visual Basic Programming", 1, 2007, 1],
  [
    "Anhang Zhu",
    "Carson Tang",
    "Nima Rahnemoon",
    "Website Development",
    1,
    2007,
    2,
  ],
  ["Hiroko Kawana", "Word Processing I", 1, 2007, 5],
  ["Cheryl Ichikawa", "Accounting I", 0, 2007, 9],
  ["James Shieh", "Accounting I", 0, 2007, 5],
  ["Keri Omuro", "Accounting I", 0, 2007, 8],
  ["Ning-Ning Ding", "Accounting I", 0, 2007, 7],
  ["Radhiya Colson", "Accounting I", 0, 2007, 10],
  ["Bob Zhao", "Accounting II", 0, 2007, 4],
  ["Claire Brubaker", "Accounting II", 0, 2007, 2],
  ["Connie Chen", "Accounting II", 0, 2007, 3],
  ["Jennifer Garnett", "Accounting II", 0, 2007, 1],
  ["Katya Tkacheva", "Accounting II", 0, 2007, 5],
  ["Stephanie Wong", "Accounting II", 0, 2007, 7],
  ["Cheryl Ichikawa", "Business Calculations", 0, 2007, 7],
  ["Eric Jin", "Business Calculations", 0, 2007, 5],
  ["Howard Li", "Business Calculations", 0, 2007, 8],
  ["Sicheng Liu", "Business Calculations", 0, 2007, 9],
  ["Chethana Damodara", "Business Communication", 0, 2007, 6],
  ["Katherine Sun", "Business Communication", 0, 2007, 5],
  ["Lillian Chen", "Business Communication", 0, 2007, 10],
  ["Eddson Alcid", "Business Law", 0, 2007, 5],
  ["Elaine Mao", "Business Law", 0, 2007, 6],
  ["Jessica Yuan", "Business Law", 0, 2007, 1],
  ["Jim Danz", "Business Law", 0, 2007, 3],
  ["Rohit Ramchandani", "Business Law", 0, 2007, 2],
  ["Spandana Pasam", "Business Law", 0, 2007, 3],
  ["Albert Wong", "Business Math", 0, 2007, 3],
  ["Easan Anlanaatham", "Business Math", 0, 2007, 9],
  ["Laurie Sartain", "Business Math", 0, 2007, 2],
  ["Ana Martynova", "Business Procedures", 0, 2007, 6],
  ["Iris Lin", "Business Procedures", 0, 2007, 4],
  ["Katherine Sun", "Business Procedures", 0, 2007, 3],
  ["Sam Rana", "Business Procedures", 0, 2007, 8],
  ["Amber Feng", "Computer Applications", 0, 2007, 1],
  ["Bhargavi Chitneni", "Computer Applications", 0, 2007, 5],
  ["Justin Bettman", "Computer Applications", 0, 2007, 8],
  ["John Chen", "Cyber Security", 0, 2007, 3],
  ["Michael Pearce", "Cyber Security", 0, 2007, 7],
  ["Nitish Aitharaju", "Cyber Security", 0, 2007, 2],
  ["Robert Fischer", "Cyber Security", 0, 2007, 5],
  ["Sheng Lu", "Cyber Security", 0, 2007, 1],
  ["Tal Levy", "Cyber Security", 0, 2007, 9],
  ["Austin Enloe", "Economics", 0, 2007, 5],
  ["Reagan Yang", "Economics", 0, 2007, 6],
  ["Yifan Li", "Economics", 0, 2007, 3],
  ["Sunny Chu", "Jim Danz", "Charles Liu", "Entrepreneurship", 0, 2007, 1],
  ["Annie Song", "FBLA Principles and Procedures", 0, 2007, 10],
  ["Ashley Ott", "FBLA Principles and Procedures", 0, 2007, 4],
  ["Irene Baker", "FBLA Principles and Procedures", 0, 2007, 6],
  ["Lucy Xu", "FBLA Principles and Procedures", 0, 2007, 3],
  ["Brenda Hwang", "Future Business Leader", 0, 2007, 1],
  ["Matthew Lee", "Future Business Leader", 0, 2007, 5],
  [
    "Yifan Li",
    "Callie Madin",
    "Aria Srinivasan",
    "Global Business",
    0,
    2007,
    2,
  ],
  ["Aria Srinivasan", "Introduction to Business", 0, 2007, 10],
  ["Bryce Wilson", "Introduction to Business", 0, 2007, 3],
  ["Leslie Chen", "Introduction to Business", 0, 2007, 7],
  ["Max Babicz", "Introduction to Business", 0, 2007, 2],
  ["Stacy Hwang", "Introduction to Business", 0, 2007, 4],
  ["Ritu Kiragi", "Introduction to Business Communication", 0, 2007, 10],
  ["Andres Gaeta", "Introduction to Technology Concepts", 0, 2007, 5],
  ["Mark Orlovsky", "Introduction to Technology Concepts", 0, 2007, 2],
  ["Max Wallack", "Introduction to Technology Concepts", 0, 2007, 3],
  ["Winston Hsu", "Introduction to Technology Concepts", 0, 2007, 1],
  ["Xin Wei", "Introduction to Technology Concepts", 0, 2007, 4],
  [
    "Evan Harris",
    "Ashley Ott",
    "Rohit Ramchandani",
    "Management Decision Making",
    0,
    2007,
    2,
  ],
  ["Annie Stoner", "Marketing", 0, 2007, 3],
  ["Brandon Lee", "Marketing", 0, 2007, 2],
  ["Charles Liu", "Marketing", 0, 2007, 1],
  ["Edward Wang", "Marketing", 0, 2007, 7],
  ["Shawn Xu", "Marketing", 0, 2007, 4],
  ["Saayeli Mukherji", "Public Speaking I", 0, 2007, 1],
  ["Sunny Chu", "Public Speaking II", 0, 2007, 5],
  ["Justin Bettman", "Spreadsheet Applications", 0, 2007, 3],
  ["Aaron Wong", "Technology Concepts", 0, 2007, 2],
  ["Anhang Zhu", "Technology Concepts", 0, 2007, 6],
  ["John Chen", "Technology Concepts", 0, 2007, 3],
  ["Nitish Aitharaju", "Technology Concepts", 0, 2007, 5],
  ["Sheng Lu", "Technology Concepts", 0, 2007, 4],
  ["Hiroko Kawana", "Word Processing I", 0, 2007, 3],
  ["Wendy Huang", "Word Processing I", 0, 2007, 6],
  ["Jessica Liou", "Word Processing II", 0, 2007, 6],
  ["Tram Hoang", "Word Processing II", 0, 2007, 5],
  ["Claire Brubaker", "Accounting I", 2, 2006, 2],
  [
    "Sunny Chu",
    "Jennifer Garnett",
    "Annie Stoner",
    "American Enterprise",
    2,
    2006,
    3,
  ],
  ["Cheryl Ichikawa", "Business Communication", 2, 2006, 10],
  ["Michael Chen", "Khang Pham", "Edward Wang", "Business Ethics", 2, 2006, 8],
  ["Nikita Khetan", "Business Law", 2, 2006, 3],
  ["Ning-Ning Ding", "Business Law", 2, 2006, 7],
  ["Nathalie Arbel", "Sunny Chu", "Carol Wong", "Business Plan", 2, 2006, 2],
  ["Yuanyu Chen", "C++ Programming", 2, 2006, 4],
  ["Aaron Wong", "Computer Concepts", 2, 2006, 1],
  ["Jim Danz", "Computer Concepts", 2, 2006, 4],
  [
    "Charles Liu",
    "Visish Srinivasan",
    "Annie Stoner",
    "Entrepreneurship",
    2,
    2006,
    3,
  ],
  ["Rohit Ramchandani", "Introduction to Business", 2, 2006, 8],
  ["Drew Haven", "Java Programming", 2, 2006, 1],
  [
    "Nitish Aitharaju",
    "Piyush Goyal",
    "Sicheng Liu",
    "Network Design",
    2,
    2006,
    2,
  ],
  ["Adrian Lam", "Accounting I", 1, 2006, 1],
  ["Claire Brubaker", "Accounting I", 1, 2006, 3],
  ["Jennifer Garnett", "Accounting I", 1, 2006, 4],
  ["Katya Tkacheva", "Accounting I", 1, 2006, 8],
  ["Charles Hug", "Accounting II", 1, 2006, 9],
  ["Claire Brubaker", "Accounting II", 1, 2006, 7],
  ["Connie Chen", "Accounting II", 1, 2006, 5],
  ["David Pochowski", "Accounting II", 1, 2006, 8],
  [
    "Annie Stoner",
    "Jennifer Garnett",
    "Sunny Chu",
    "American Enterprise",
    1,
    2006,
    2,
  ],
  ["Zachary Colbeth", "Banking and Financial Systems", 1, 2006, 6],
  ["Cheryl Ichikawa", "Business Communication", 1, 2006, 6],
  ["Lillian Chen", "Business Communication", 1, 2006, 5],
  ["Michael Chen", "Edward Wang", "Khang Pham", "Business Ethics", 1, 2006, 1],
  ["Brenda Boyle", "Business Law", 1, 2006, 4],
  ["Eric Jin", "Business Law", 1, 2006, 5],
  ["Ginny Van", "Business Law", 1, 2006, 6],
  ["Jim Danz", "Business Law", 1, 2006, 2],
  ["Nikita Khetan", "Business Law", 1, 2006, 1],
  ["Ning-Ning Ding", "Business Law", 1, 2006, 3],
  ["Drew Haven", "Business Math", 1, 2006, 3],
  ["Rohit Ramchandani", "Business Math", 1, 2006, 4],
  ["Nathalie Arbel", "Carol Wong", "Sunny Chu", "Business Plan", 1, 2006, 2],
  ["Carson Tang", "C++ Programming", 1, 2006, 5],
  ["Marcos Gaeta", "C++ Programming", 1, 2006, 4],
  ["Stanley Szeto", "C++ Programming", 1, 2006, 3],
  ["Yuanyu Chen", "C++ Programming", 1, 2006, 1],
  [
    "Emma Tolley",
    "Brenda Hwang",
    "Mary Plavec",
    "Community Service",
    1,
    2006,
    2,
  ],
  ["Aaron Wong", "Computer Concepts", 1, 2006, 2],
  ["Amber Feng", "Computer Concepts", 1, 2006, 7],
  ["Jim Danz", "Computer Concepts", 1, 2006, 1],
  ["Matthew Lee", "Creed", 1, 2006, 6],
  ["Iris Lin", "Kevin Zhang", "Desktop Publishing", 1, 2006, 5],
  [
    "Visish Srinivasan",
    "Katherine Sun",
    "Charles Liu",
    "Dr. Jessie Graham Award",
    1,
    2006,
    -3,
  ],
  [
    "Carson Tang",
    "Shawn Xu",
    "Yifan Li",
    "Emerging Business Issues",
    1,
    2006,
    4,
  ],
  [
    "Visish Srinivasan",
    "Charles Liu",
    "Annie Stoner",
    "Entrepreneurship",
    1,
    2006,
    1,
  ],
  ["Ashley Ott", "FBLA Principles and Procedures", 1, 2006, 8],
  ["Michael Chen", "Future Business Leader", 1, 2006, 2],
  ["Charles Liu", "International Business", 1, 2006, 1],
  ["Visish Srinivasan", "International Business", 1, 2006, 8],
  ["Max Babicz", "Introduction to Business", 1, 2006, 7],
  ["Rohit Ramchandani", "Introduction to Business", 1, 2006, 1],
  ["Shawn Xu", "Introduction to Business", 1, 2006, 6],
  ["Chethana Damodara", "Introduction to Business Communication", 1, 2006, 5],
  ["Alex Shiroglazov", "Introduction to Parliamentary Procedure", 1, 2006, 4],
  ["Emerald Chun", "Introduction to Parliamentary Procedure", 1, 2006, 7],
  ["Krzys Brozek", "Introduction to Parliamentary Procedure", 1, 2006, 9],
  ["Aaron Wong", "Java Programming", 1, 2006, 2],
  ["Amber Feng", "Java Programming", 1, 2006, 5],
  ["Drew Haven", "Java Programming", 1, 2006, 1],
  [
    "Visish Srinivasan",
    "Katherine Sun",
    "Charles Liu",
    "Local Chapter Annual Business Report",
    1,
    2006,
    3,
  ],
  ["Edward Wang", "Marketing", 1, 2006, 7],
  [
    "Emma Tolley",
    "Michael Pearce",
    "Wendy Huang",
    "Multimedia Presentation",
    1,
    2006,
    1,
  ],
  [
    "Piyush Goyal",
    "Nitish Aitharaju",
    "Sicheng Liu",
    "Network Design",
    1,
    2006,
    3,
  ],
  [
    "Edward Wang",
    "Eddson Alcid",
    "Shawn Xu",
    "Partnership with Business",
    1,
    2006,
    2,
  ],
  ["Homestead", "Sweepstakes", 1, 2006, 1],
  ["Nitish Aitharaju", "Technology Concepts", 1, 2006, 7],
  ["Niranjan Manoharan", "Visual Basic Programming", 1, 2006, 8],
  ["Adrian Lam", "Accounting I", 0, 2006, 8],
  ["Claire Brubaker", "Accounting I", 0, 2006, 4],
  ["Jennifer Garnett", "Accounting I", 0, 2006, 2],
  ["Jennifer Wang", "Accounting I", 0, 2006, 10],
  ["Katya Tkacheva", "Accounting I", 0, 2006, 7],
  ["Zachary Colbeth", "Accounting I", 0, 2006, 9],
  ["Charles Hug", "Accounting II", 0, 2006, 4],
  ["Claire Brubaker", "Accounting II", 0, 2006, 5],
  ["Connie Chen", "Accounting II", 0, 2006, 2],
  ["David Pochowski", "Accounting II", 0, 2006, 3],
  ["Jenny Popova", "Accounting II", 0, 2006, 6],
  ["Stephanie Wong", "Accounting II", 0, 2006, 9],
  ["Eddson Alcid", "Business Calculations", 0, 2006, 4],
  ["Yifan Li", "Business Calculations", 0, 2006, 3],
  ["Cheryl Ichikawa", "Business Communication", 0, 2006, 5],
  ["Lillian Chen", "Business Communication", 0, 2006, 2],
  ["Brenda Boyle", "Business Law", 0, 2006, 3],
  ["Eric Jin", "Business Law", 0, 2006, 5],
  ["Ginny Van", "Business Law", 0, 2006, 6],
  ["Jim Danz", "Business Law", 0, 2006, 2],
  ["Nikita Khetan", "Business Law", 0, 2006, 1],
  ["Ning-Ning Ding", "Business Law", 0, 2006, 4],
  ["David Strickland", "Business Math", 0, 2006, 10],
  ["Drew Haven", "Business Math", 0, 2006, 4],
  ["Rohit Ramchandani", "Business Math", 0, 2006, 3],
  ["Yuanyu Chen", "Business Math", 0, 2006, 7],
  ["Iris Lin", "Business Procedures", 0, 2006, 6],
  ["Katherine Sun", "Business Procedures", 0, 2006, 7],
  ["Sam Rana", "Business Procedures", 0, 2006, 10],
  ["Shih-Paul Chen", "Business Procedures", 0, 2006, 9],
  ["Robert Fischer", "Computer Applications", 0, 2006, 1],
  ["Aaron Wong", "Computer Concepts", 0, 2006, 1],
  ["Amber Feng", "Computer Concepts", 0, 2006, 6],
  ["Drew Haven", "Computer Concepts", 0, 2006, 5],
  ["James Tran", "Computer Concepts", 0, 2006, 9],
  ["Jim Danz", "Computer Concepts", 0, 2006, 3],
  ["Yuanyu Chen", "Computer Concepts", 0, 2006, 7],
  ["Matthew Lee", "Creed Contest", 0, 2006, 3],
  ["Simon Iacob", "Economics", 0, 2006, 5],
  ["Visish Srinivasan", "Economics", 0, 2006, 9],
  [
    "Visish Srinivasan",
    "Annie Stoner",
    "Charles Liu",
    "Entrepreneurship",
    0,
    2006,
    1,
  ],
  ["Ashley Ott", "FBLA Principles and Procedures", 0, 2006, 6],
  ["Emerald Chun", "FBLA Principles and Procedures", 0, 2006, 9],
  ["Krzys Brozek", "FBLA Principles and Procedures", 0, 2006, 10],
  ["Matthew Lee", "FBLA Principles and Procedures", 0, 2006, 7],
  ["Stephanie Zau", "FBLA Principles and Procedures", 0, 2006, 2],
  ["Lulu Lin", "Future Business Leader", 0, 2006, 3],
  ["Michael Chen", "Future Business Leader", 0, 2006, 2],
  ["Chris Phillips", "Introduction to Business", 0, 2006, 8],
  ["Clara Lee", "Introduction to Business", 0, 2006, 9],
  ["Max Babicz", "Introduction to Business", 0, 2006, 3],
  ["Rohit Ramchandani", "Introduction to Business", 0, 2006, 2],
  ["Shawn Xu", "Introduction to Business", 0, 2006, 5],
  ["Stacy Hwang", "Introduction to Business", 0, 2006, 7],
  ["Chethana Damodara", "Introduction to Business Communication", 0, 2006, 3],
  ["Eric Pai", "Introduction to Business Communication", 0, 2006, 8],
  ["Khang Pham", "Job Interview", 0, 2006, 7],
  ["Piyush Goyal", "Job Interview", 0, 2006, 2],
  ["Brandon Lee", "Marketing", 0, 2006, 6],
  ["Edward Wang", "Marketing", 0, 2006, 4],
  ["Radhiya Colson", "Marketing", 0, 2006, 7],
  ["Sunny Chu", "Public Speaking II", 0, 2006, 2],
  ["Nitish Aitharaju", "Technology Concepts", 0, 2006, 5],
  ["Robert Fischer", "Technology Concepts", 0, 2006, 9],
  ["Simon Iacob", "Technology Concepts", 0, 2006, 7],
  ["Mark Sagherian", "Word Processing I", 0, 2006, 8],
  ["Tram Hoang", "Word Processing I", 0, 2006, 10],
  ["Bill Fickett", "Word Processing II", 0, 2006, 6],
  ["Wendy Huang", "Word Processing II", 0, 2006, 10],
  ["Charles Liu", "Business Law", 2, 2005, 3],
  ["Zachary Colbeth", "Business Law", 2, 2005, 4],
  [
    "Visish Srinivasan",
    "Michael Chen",
    "Albert Yen",
    "Entrepreneurship",
    2,
    2005,
    3,
  ],
  ["Jim Danz", "Java Programming", 2, 2005, 2],
  ["Nitish Aitharaju", "Java Programming", 2, 2005, 9],
  [
    "Adela Mou",
    "Albert Yen",
    "Charles Liu",
    "Partnership with Business",
    2,
    2005,
    5,
  ],
  ["Connie Chen", "Accounting I", 1, 2005, 7],
  ["Jenny Popova", "Accounting I", 1, 2005, 8],
  ["Meena Siddiqui", "Accounting I", 1, 2005, 1],
  ["Scott Payne", "Accounting I", 1, 2005, 6],
  ["Connie Chen", "Accounting II", 1, 2005, 8],
  ["Geoffrey Bazinett", "Accounting II", 1, 2005, 3],
  ["Helen Ye", "Accounting II", 1, 2005, 2],
  ["Jennifer Sheu", "Accounting II", 1, 2005, 4],
  [
    "Danielle Crawford",
    "Kenan Frager",
    "Michelle Ton",
    "American Enterprise",
    1,
    2005,
    3,
  ],
  ["Jackie Laird", "Banking and Financial Systems", 1, 2005, 8],
  ["Laura Kuo", "Banking and Financial Systems", 1, 2005, 1],
  ["Laura Kuo", "Business Calculations", 1, 2005, 5],
  ["Charles Liu", "Business Law", 1, 2005, 1],
  ["Danielle Crawford", "Business Law", 1, 2005, 5],
  ["Ginny Van", "Business Law", 1, 2005, 9],
  ["Kenan Frager", "Business Law", 1, 2005, 6],
  ["Visish Srinivasan", "Business Law", 1, 2005, 4],
  ["Zachary Colbeth", "Business Law", 1, 2005, 2],
  ["Xavier Gaeta", "Lunani Yen", "Boyuan Zhu", "Business Plan", 1, 2005, 1],
  ["Sam Rana", "Business Procedures", 1, 2005, 6],
  ["Scott Ichikawa", "C++ Programming", 1, 2005, 10],
  ["Xavier Gaeta", "C++ Programming", 1, 2005, 5],
  [
    "Geoffrey Bazinett",
    "Boyuan Zhu",
    "Lunani Yen",
    "Community Service",
    1,
    2005,
    3,
  ],
  ["Jim Danz", "Computer Concepts", 1, 2005, 3],
  ["Nitish Aitharaju", "Computer Concepts", 1, 2005, 8],
  [
    "Helen Wu",
    "Ani Goranova",
    "Serena Mau",
    "Dr. Jessie Graham Award",
    1,
    2005,
    -1,
  ],
  [
    "Ani Goranova",
    "Min Park",
    "Annie Stoner",
    "Emerging Business Issues",
    1,
    2005,
    3,
  ],
  [
    "Michael Chen",
    "Visish Srinivasan",
    "Albert Yen",
    "Entrepreneurship",
    1,
    2005,
    1,
  ],
  ["Brandon Lee", "International Business", 1, 2005, 9],
  ["Daniel Wright", "International Business", 1, 2005, 10],
  ["Tanya Sachdeva", "International Business", 1, 2005, 2],
  ["Brenda Hwang", "Introduction to Business", 1, 2005, 6],
  ["Eddson Alcid", "Introduction to Business", 1, 2005, 2],
  ["Ning-Ning Ding", "Introduction to Business", 1, 2005, 4],
  ["Cheryl Ichikawa", "Introduction to Business Communication", 1, 2005, 10],
  ["Jim Danz", "Java Programming", 1, 2005, 1],
  ["Nitish Aitharaju", "Java Programming", 1, 2005, 3],
  ["Helen Wu", "Local Chapter Annual Business Report", 1, 2005, 3],
  ["Albert Yen", "Marketing", 1, 2005, 2],
  ["Helen Wu", "Marketing", 1, 2005, 4],
  ["Scott Ichikawa", "Marketing", 1, 2005, 5],
  [
    "Emma Tolley",
    "Michael Pearce",
    "Matthew Lee",
    "Multimedia Presentation",
    1,
    2005,
    3,
  ],
  ["Piyush Goyal", "Simon Iacob", "Edward Wang", "Network Design", 1, 2005, 1],
  [
    "Albert Yen",
    "Adela Mou",
    "Charles Liu",
    "Partnership with Business",
    1,
    2005,
    1,
  ],
  ["Homestead", "Sweepstakes", 1, 2005, 1],
  ["Iris Lin", "Visual Basic Programming", 1, 2005, 10],
  ["Niranjan Manoharan", "Visual Basic Programming", 1, 2005, 5],
  ["Phillip Tao", "Visual Basic Programming", 1, 2005, 2],
  ["Connie Chen", "Accounting I", 0, 2005, 3],
  ["David Pochowski", "Accounting I", 0, 2005, 7],
  ["Jenny Popova", "Accounting I", 0, 2005, 4],
  ["Kenan Frager", "Accounting I", 0, 2005, 8],
  ["Meena Siddiqui", "Accounting I", 0, 2005, 1],
  ["Scott Payne", "Accounting I", 0, 2005, 2],
  ["Connie Chen", "Accounting II", 0, 2005, 4],
  ["Danielle Galeano", "Accounting II", 0, 2005, 6],
  ["Geoffrey Bazinett", "Accounting II", 0, 2005, 2],
  ["Helen Ye", "Accounting II", 0, 2005, 1],
  ["Jennifer Sheu", "Accounting II", 0, 2005, 3],
  ["Meena Siddiqui", "Accounting II", 0, 2005, 5],
  ["Adela Mou", "Business Calculations", 0, 2005, 4],
  ["Eddson Alcid", "Business Calculations", 0, 2005, 7],
  ["Laura Kuo", "Business Calculations", 0, 2005, 1],
  ["Nathalie Arbel", "Business Communication", 0, 2005, 8],
  ["Charles Liu", "Business Law", 0, 2005, 1],
  ["Danielle Crawford", "Business Law", 0, 2005, 2],
  ["Ginny Van", "Business Law", 0, 2005, 6],
  ["Kenan Frager", "Business Law", 0, 2005, 5],
  ["Visish Srinivasan", "Business Law", 0, 2005, 3],
  ["Zachary Colbeth", "Business Law", 0, 2005, 4],
  ["David Strickland", "Business Math", 0, 2005, 9],
  ["Krzysztof Brozek", "Business Math", 0, 2005, 8],
  ["Michelle Ton", "Business Procedures", 0, 2005, 10],
  ["Paul Chen", "Business Procedures", 0, 2005, 6],
  ["Xavier Gaeta", "Business Procedures", 0, 2005, 1],
  ["Jim Danz", "Computer Applications", 0, 2005, 5],
  ["Edward Wang", "Computer Concepts", 0, 2005, 5],
  ["Iris Lin", "Computer Concepts", 0, 2005, 10],
  ["Jim Danz", "Computer Concepts", 0, 2005, 1],
  ["Nitish Aitharaju", "Computer Concepts", 0, 2005, 2],
  ["Matthew Lee", "Creed Contest", 0, 2005, 3],
  ["Adela Mou", "Economics", 0, 2005, 6],
  ["Ani Goranova", "Economics", 0, 2005, 7],
  ["Laura Kuo", "Economics", 0, 2005, 9],
  ["Serena Mau", "Economics", 0, 2005, 5],
  [
    "Albert Yen",
    "Michael Chen",
    "Visish Srinivasan",
    "Entrepreneurship",
    0,
    2005,
    1,
  ],
  ["Brenda Boyle", "FBLA Principles and Procedures", 0, 2005, 8],
  ["Radhiya Colson", "FBLA Principles and Procedures", 0, 2005, 10],
  ["Cory O'Yang", "Future Business Leader", 0, 2005, 2],
  ["Piyush Goyal", "Future Business Leader", 0, 2005, 7],
  ["Ben Lewis", "Introduction to Business", 0, 2005, 8],
  ["Brandon Lee", "Introduction to Business", 0, 2005, 10],
  ["Brenda Hwang", "Introduction to Business", 0, 2005, 6],
  ["Chethana Damodara", "Introduction to Business", 0, 2005, 4],
  ["Eddson Alcid", "Introduction to Business", 0, 2005, 2],
  ["Ning-Ning Ding", "Introduction to Business", 0, 2005, 1],
  ["Cheryl Ichikawa", "Introduction to Business Communication", 0, 2005, 3],
  ["Katherine Sun", "Introduction to Business Communication", 0, 2005, 4],
  ["Nicole Lew", "Introduction to Business Communication", 0, 2005, 8],
  ["Piyush Goyal", "Job Interview", 0, 2005, 4],
  ["Albert Yen", "Marketing", 0, 2005, 4],
  ["Carol Wong", "Marketing", 0, 2005, 10],
  ["Helen Wu", "Marketing", 0, 2005, 5],
  ["Michael Chen", "Marketing", 0, 2005, 7],
  ["Scott Ichikawa", "Marketing", 0, 2005, 2],
  ["Michael Pearce", "Public Speaking I", 0, 2005, 5],
  ["Ani Goranova", "Public Speaking II", 0, 2005, 3],
  ["Boyuan Zhu", "Technology Concepts", 0, 2005, 1],
  ["Lunani Yen", "Technology Concepts", 0, 2005, 9],
  ["Simon Iacob", "Technology Concepts", 0, 2005, 8],
  ["Bill Fickett", "Word Processing II", 0, 2005, 6],
  ["Lunani Yen", "Word Processing II", 0, 2005, 5],
  [
    "AJ Lee",
    "Angela Contreras",
    "Ani Goranova",
    "American Enterprise",
    2,
    2004,
    2,
  ],
  ["Rachel Nelson", "Business Law", 2, 2004, 1],
  ["Eddson Alcid", "Business Math", 2, 2004, 8],
  ["Angela Contreras", "Business Plan", 2, 2004, 6],
  [
    "Jo Lin",
    "Min Park",
    "Scott Ichikawa",
    "Emerging Business Issues",
    2,
    2004,
    4,
  ],
  [
    "Boyuan Zhu",
    "Scott Graves",
    "Xavier Gaeta",
    "Entrepreneurship",
    2,
    2004,
    1,
  ],
  ["Kim Luong", "International Business", 2, 2004, 3],
  ["Bhavna Muthangi", "Marketing", 2, 2004, 3],
  [
    "Boyuan Zhu",
    "Xavier Gaeta",
    "Albert Yen",
    "Partnership with Business",
    2,
    2004,
    1,
  ],
  ["Albert Yen", "Accounting I", 1, 2004, 5],
  ["Jennifer Sheu", "Accounting I", 1, 2004, 2],
  ["Kim Phan", "Accounting I", 1, 2004, 7],
  ["Meena Siddiqui", "Accounting I", 1, 2004, 3],
  ["Albert Yen", "Accounting II", 1, 2004, 2],
  ["Helen Ye", "Accounting II", 1, 2004, 3],
  ["Jennifer Sheu", "Accounting II", 1, 2004, 4],
  ["Laura Kuo", "Accounting II", 1, 2004, 1],
  [
    "AJ Lee",
    "Angela Contreras",
    "Ani Goranova",
    "American Enterprise",
    1,
    2004,
    1,
  ],
  ["Jackie Laird", "Banking and Financial Systems", 1, 2004, 3],
  ["Kim Phan", "Banking and Financial Systems", 1, 2004, 4],
  ["Min Park", "Banking and Financial Systems", 1, 2004, 6],
  ["Serena Mau", "Banking and Financial Systems", 1, 2004, 1],
  ["Adela Mou", "Business Calculations", 1, 2004, 8],
  ["Laurence Jiang", "Business Calculations", 1, 2004, 5],
  ["Dang Nguyen", "Business Communication", 1, 2004, 9],
  ["Derrick Tang", "Business Communication", 1, 2004, 3],
  ["Cory O'Yang", "Business Law", 1, 2004, 5],
  ["Daniel Wright", "Business Law", 1, 2004, 4],
  ["Kim Luong", "Business Law", 1, 2004, 2],
  ["Laurence Jiang", "Business Law", 1, 2004, 7],
  ["Rachel Nelson", "Business Law", 1, 2004, 3],
  ["Serena Mau", "Business Law", 1, 2004, 8],
  ["Adrian Lam", "Business Math", 1, 2004, 9],
  ["Eddson Alcid", "Business Math", 1, 2004, 1],
  [
    "Angela Contreras",
    "Ani Goranova",
    "Arman Zahoory",
    "Business Plan",
    1,
    2004,
    2,
  ],
  ["Jo Lin", "Business Procedures", 1, 2004, 2],
  ["Beverly Sum", "C++ Programming", 1, 2004, 6],
  ["Derrick Tang", "C++ Programming", 1, 2004, 2],
  ["Xavier Gaeta", "C++ Programming", 1, 2004, 1],
  ["Lunani Yen", "Cory O'Yang", "Carol Wong", "Community Service", 1, 2004, 4],
  ["Lucy Chen", "Computer Applications", 1, 2004, 4],
  ["Galina Shpuntova", "Computer Concepts", 1, 2004, 5],
  ["Piyush Goyal", "Computer Concepts", 1, 2004, 8],
  ["AJ Lee", "Kelly Kato", "Desktop Publishing", 1, 2004, 9],
  ["Bhavna Muthangi", "Economics", 1, 2004, 1],
  [
    "Jo Lin",
    "Min Park",
    "Scott Ichikawa",
    "Emerging Business Issues",
    1,
    2004,
    2,
  ],
  [
    "Boyuan Zhu",
    "Scott Graves",
    "Xavier Gaeta",
    "Entrepreneurship",
    1,
    2004,
    1,
  ],
  ["Scott Graves", "Future Business Leader", 1, 2004, 7],
  ["Danielle Crawford", "Impromptu Speaking", 1, 2004, 9],
  ["Carol Wong", "International Business", 1, 2004, 9],
  ["Daniel Wright", "International Business", 1, 2004, 4],
  ["Kim Luong", "International Business", 1, 2004, 2],
  ["Tanya Sachdeva", "International Business", 1, 2004, 5],
  ["Ning-Ning Ding", "Introduction to Business", 1, 2004, 4],
  ["Visish Srinivasan", "Introduction to Business", 1, 2004, 3],
  ["Cheryl Ichikawa", "Introduction to Business Communication", 1, 2004, 6],
  ["Galina Shpuntova", "Java Programming", 1, 2004, 10],
  ["Piyush Goyal", "Java Programming", 1, 2004, 6],
  ["Bhavna Muthangi", "L. Byram Bates $1000 Scholarship", 1, 2004, -2],
  ["Scott Graves", "Local Chapter Annual Business Report", 1, 2004, 4],
  ["Angela Contreras", "Marketing", 1, 2004, 5],
  ["Bhavna Muthangi", "Marketing", 1, 2004, 1],
  [
    "Jeffrey Lin",
    "Kelly Kato",
    "Lunani Yen",
    "Multimedia Presentation",
    1,
    2004,
    2,
  ],
  ["Vincent Chuang", "Networking Concepts", 1, 2004, 8],
  [
    "Boyuan Zhu",
    "Xavier Gaeta",
    "Albert Yen",
    "Partnership with Business",
    1,
    2004,
    1,
  ],
  ["David Pochowski", "Public Speaking I", 1, 2004, 6],
  ["Arman Zahoory", "Public Speaking II", 1, 2004, 3],
  ["Homestead", "Sweepstakes", 1, 2004, 1],
  ["Dang Nguyen", "Visual Basic Programming", 1, 2004, 3],
  ["Michael Chen", "Visual Basic Programming", 1, 2004, 10],
  ["Phillip Tao", "Visual Basic Programming", 1, 2004, 4],
  ["Vincent Chuang", "Visual Basic Programming", 1, 2004, 7],
  ["Albert Yen", "Accounting I", 0, 2004, 2],
  ["Ani Goranova", "Accounting I", 0, 2004, 5],
  ["Annie Liou", "Accounting I", 0, 2004, 7],
  ["Jennifer Sheu", "Accounting I", 0, 2004, 3],
  ["Kim Phan", "Accounting I", 0, 2004, 4],
  ["Meena Siddiqui", "Accounting I", 0, 2004, 1],
  ["Albert Yen", "Accounting II", 0, 2004, 2],
  ["Geoffrey Bazinett", "Accounting II", 0, 2004, 4],
  ["Helen Ye", "Accounting II", 0, 2004, 3],
  ["Jennifer Sheu", "Accounting II", 0, 2004, 5],
  ["Laura Kuo", "Accounting II", 0, 2004, 1],
  ["Adela Mou", "Business Calculations", 0, 2004, 5],
  ["Laura Kuo", "Business Calculations", 0, 2004, 4],
  ["Laurence Jiang", "Business Calculations", 0, 2004, 1],
  ["Scott Payne", "Business Calculations", 0, 2004, 2],
  ["Boyuan Zhu", "Business Communication", 0, 2004, 4],
  ["Dang Nguyen", "Business Communication", 0, 2004, 3],
  ["Derrick Tang", "Business Communication", 0, 2004, 2],
  ["Qian Chen", "Business Communication", 0, 2004, 7],
  ["Cory O'Yang", "Business Law", 0, 2004, 2],
  ["Daniel Wright", "Business Law", 0, 2004, 1],
  ["Kim Luong", "Business Law", 0, 2004, 6],
  ["Laurence Jiang", "Business Law", 0, 2004, 5],
  ["Rachel Nelson", "Business Law", 0, 2004, 3],
  ["Serena Mau", "Business Law", 0, 2004, 7],
  ["Adrian Lam", "Business Math", 0, 2004, 5],
  ["Eddson Alcid", "Business Math", 0, 2004, 4],
  ["Jackie Laird", "Business Procedures", 0, 2004, 6],
  ["Jo Lin", "Business Procedures", 0, 2004, 5],
  ["Kenan Frager", "Business Procedures", 0, 2004, 7],
  ["Michelle Ton", "Business Procedures", 0, 2004, 4],
  ["Lucy Chen", "Computer Applications", 0, 2004, 2],
  ["Rishi Agrawal", "Computer Applications", 0, 2004, 7],
  ["Galina Shpuntova", "Computer Concepts", 0, 2004, 2],
  ["Nitish Aitharaju", "Computer Concepts", 0, 2004, 9],
  ["Piyush Goyal", "Computer Concepts", 0, 2004, 5],
  ["Visish Srinivasan", "Computer Concepts", 0, 2004, 3],
  ["Kenan Frager", "Creed", 0, 2004, 3],
  ["Bhavna Muthangi", "Economics", 0, 2004, 1],
  ["Jo Lin", "Economics", 0, 2004, 3],
  ["Kamil Brozek", "Economics", 0, 2004, 6],
  [
    "Boyuan Zhu",
    "Scott Graves",
    "Xavier Gaeta",
    "Entrepreneurship",
    0,
    2004,
    1,
  ],
  ["April Baker", "FBLA Principles and Procedures", 0, 2004, 7],
  ["Jackie Laird", "Future Business Leader", 0, 2004, 4],
  ["Scott Graves", "Future Business Leader", 0, 2004, 1],
  ["Ben Lewis", "Introduction to Business", 0, 2004, 6],
  ["Carol Wong", "Introduction to Business", 0, 2004, 10],
  ["Ning-Ning Ding", "Introduction to Business", 0, 2004, 5],
  ["Visish Srinivasan", "Introduction to Business", 0, 2004, 1],
  ["Cheryl Ichikawa", "Introduction to Business Communication", 0, 2004, 4],
  ["John Acosta", "Job Interview", 0, 2004, 4],
  ["Angela Contreras", "Marketing", 0, 2004, 3],
  ["Bhavna Muthangi", "Marketing", 0, 2004, 1],
  ["Helen Wu", "Marketing", 0, 2004, 6],
  ["Wayne Hsieh", "Marketing", 0, 2004, 9],
  ["David Pochowski", "Public Speaking I", 0, 2004, 3],
  ["Arman Zahoory", "Public Speaking II", 0, 2004, 1],
  ["Dan Wallner", "Technology Concepts", 0, 2004, 4],
  ["Lucy Chen", "Technology Concepts", 0, 2004, 3],
  ["Vincent Chuang", "Technology Concepts", 0, 2004, 7],
  ["Kelly Kato", "Word Processing I", 0, 2004, 7],
  ["Roger Tjhia", "Word Processing I", 0, 2004, 8],
  ["Phillip Tao", "Word Processing II", 0, 2004, 3],
  ["Bhavna Muthangi", "Advertising (Open Event)", 2, 2003, 2],
  ["Clarence Yung", "Advertising (Open Event)", 2, 2003, 1],
  [
    "Janette Wong",
    "Aditi Goel",
    "Sadaf Shahsahebi",
    "American Enterprise",
    2,
    2003,
    5,
  ],
  ["Laurence Jiang", "Banking and Financial Systems", 2, 2003, 5],
  ["Ani Goranova", "Business Law", 2, 2003, 2],
  ["Grace Luo", "Business Law", 2, 2003, 1],
  ["Xavier Gaeta", "Business Math", 2, 2003, 7],
  [
    "Michael Sheppard",
    "Angela Contreras",
    "Daniel Wright",
    "Business Plan",
    2,
    2003,
    5,
  ],
  ["Jeff Chen", "Business Procedures", 2, 2003, 6],
  ["Boyuan Zhu", "C++ Programming", 2, 2003, 3],
  [
    "Jo Lin",
    "Scott Graves",
    "Jackie Laird",
    "Emerging Business Issues",
    2,
    2003,
    10,
  ],
  [
    "Corey Reese",
    "Bhavna Muthangi",
    "Vivian Chen",
    "Entrepreneurship",
    2,
    2003,
    2,
  ],
  ["Bhavna Muthangi", "Insurance Operations (Open Event)", 2, 2003, 2],
  ["Kim Luong", "Introduction to Business", 2, 2003, 4],
  ["Corey Reese", "Leadership (Open Event)", 2, 2003, 2],
  ["Clarence Yung", "Marketing", 2, 2003, 1],
  [
    "Carl Cheng",
    "Jeff Lin",
    "Kamil Brozek",
    "Multimedia Presentation",
    2,
    2003,
    3,
  ],
  ["Helen Ye", "Accounting I", 1, 2003, 5],
  ["Laura Kuo", "Accounting I", 1, 2003, 1],
  ["John Bereznak", "Accounting II", 1, 2003, 3],
  ["Laura Kuo", "Accounting II", 1, 2003, 1],
  ["Janette Wong", "Aditi Goel", "American Enterprise", 1, 2003, 1],
  ["Laurence Jiang", "Banking and Financial Systems", 1, 2003, 1],
  ["Laurence Jiang", "Business Calculations", 1, 2003, 2],
  ["Alan Chang", "Business Communication", 1, 2003, 3],
  ["Derrick Tang", "Business Communication", 1, 2003, 4],
  ["Ani Goranova", "Business Law", 1, 2003, 2],
  ["Daniel Wright", "Business Law", 1, 2003, 4],
  ["Grace Luo", "Business Law", 1, 2003, 1],
  ["Haley Simon", "Business Law", 1, 2003, 3],
  ["Rachel Nelson", "Business Law", 1, 2003, 8],
  ["Xavier Gaeta", "Business Math", 1, 2003, 2],
  [
    "Angela Contreras",
    "Michael Sheppard",
    "Daniel Wright",
    "Business Plan",
    1,
    2003,
    2,
  ],
  ["Jeff Chen", "Business Procedures", 1, 2003, 3],
  ["Jo Lin", "Business Procedures", 1, 2003, 4],
  ["Boyuan Zhu", "C++ Programming", 1, 2003, 1],
  ["Dang Nguyen", "C++ Programming", 1, 2003, 8],
  ["Xavier Gaeta", "C++ Programming", 1, 2003, 2],
  [
    "Vivian Chen",
    "Laurence Jiang",
    "Lunani Yen",
    "Community Service",
    1,
    2003,
    3,
  ],
  ["Shahin Saneinejad", "Computer Concepts", 1, 2003, 7],
  [
    "AJ Lee",
    "Grace Luo",
    "Clarence Yung",
    "Dr. Jessie Graham Award",
    1,
    2003,
    2,
  ],
  ["Corey Reese", "Economics", 1, 2003, 4],
  [
    "Scott Graves",
    "Zachary Landes",
    "Jo Lin",
    "Emerging Business Issues",
    1,
    2003,
    1,
  ],
  [
    "Vivian Chen",
    "Bhavna Muthangi",
    "Corey Reese",
    "Entrepreneurship",
    1,
    2003,
    1,
  ],
  ["Helen Wu", "FBLA Principles and Procedures", 1, 2003, 2],
  ["Jackie Laird", "FBLA Principles and Procedures", 1, 2003, 3],
  ["Jennifer Sheu", "FBLA Principles and Procedures", 1, 2003, 5],
  ["Lillian Lee", "FBLA Principles and Procedures", 1, 2003, 10],
  ["Clarence Yung", "Future Business Leader", 1, 2003, 1],
  ["Andrea Lam", "International Business", 1, 2003, 4],
  ["Janette Wong", "International Business", 1, 2003, 2],
  ["Thomas Ni", "International Business", 1, 2003, 6],
  ["Boyuan Zhu", "Introduction to Business", 1, 2003, 3],
  ["Cory O'Yang", "Introduction to Business", 1, 2003, 2],
  ["Kim Luong", "Introduction to Business", 1, 2003, 1],
  ["Serena Mau", "Introduction to Business", 1, 2003, 8],
  ["Brian Chang", "Java Programming", 1, 2003, 9],
  ["Scott Graves", "Java Programming", 1, 2003, 4],
  ["Sadaf Shahsahebi", "Job Interview", 1, 2003, 7],
  [
    "Grace Luo",
    "Clarence Yung",
    "Local Chapter Annual Business Report",
    1,
    2003,
    3,
  ],
  ["Andrea Lam", "Marketing", 1, 2003, 4],
  ["Bhavna Muthangi", "Marketing", 1, 2003, 1],
  ["Clarence Yung", "Marketing", 1, 2003, 2],
  [
    "Kamil Brozek",
    "Carl Cheng",
    "Jeff Lin",
    "Multimedia Presentation",
    1,
    2003,
    1,
  ],
  ["Brian Wiebe", "Scott Ichikawa", "Network Design", 1, 2003, 3],
  ["Visish Srinivasan", "Networking Concepts", 1, 2003, 3],
  [
    "Angela Contreras",
    "Albert Yen",
    "Boyuan Zhu",
    "Partnership with Business",
    1,
    2003,
    1,
  ],
  ["Aditi Goel", "Public Speaking I", 1, 2003, 2],
  ["Homestead", "Sweepstakes", 1, 2003, 1],
  ["Brian Wiebe", "Technology Concepts", 1, 2003, 9],
  ["Shahin Saneinejad", "Visual Basic Programming", 1, 2003, 8],
  [
    "Carl Cheng",
    "Visish Srinivasan",
    "Lunani Yen",
    "Website Development",
    1,
    2003,
    9,
  ],
  ["Sadaf Shahsahebi", "Word Processing II", 1, 2003, 9],
  ["Carrine Chan", "Accounting I", 0, 2003, 6],
  ["Helen Ye", "Accounting I", 0, 2003, 2],
  ["Kim Phan", "Accounting I", 0, 2003, 8],
  ["Laura Kuo", "Accounting I", 0, 2003, 1],
  ["Daisy Tran", "Accounting II", 0, 2003, 4],
  ["Helen Ye", "Accounting II", 0, 2003, 8],
  ["John Bereznak", "Accounting II", 0, 2003, 3],
  ["Laura Kuo", "Accounting II", 0, 2003, 1],
  ["Michael Sheppard", "Accounting II", 0, 2003, 5],
  ["Carl Cheng", "Business Calculations", 0, 2003, 8],
  ["Laurence Jiang", "Business Calculations", 0, 2003, 2],
  ["Qian Chen", "Business Calculations", 0, 2003, 5],
  ["Alan Chang", "Business Communication", 0, 2003, 1],
  ["Derrick Tang", "Business Communication", 0, 2003, 6],
  ["Katherine Lao", "Business Communication", 0, 2003, 4],
  ["Daniel Wright", "Business Law", 0, 2003, 2],
  ["Grace Luo", "Business Law", 0, 2003, 1],
  ["Haley Simon", "Business Law", 0, 2003, 6],
  ["Rachel Nelson", "Business Law", 0, 2003, 5],
  ["Scott Graves", "Business Law", 0, 2003, 8],
  ["Xavier Gaeta", "Business Math", 0, 2003, 3],
  ["Arcadi Kolchak", "Business Procedures", 0, 2003, 8],
  ["Jeff Chen", "Business Procedures", 0, 2003, 1],
  ["Jo Lin", "Business Procedures", 0, 2003, 3],
  ["Lucy Chen", "Computer Applications", 0, 2003, 9],
  ["Dang Nguyen", "Computer Concepts", 0, 2003, 7],
  ["Shahin Saneinejad", "Computer Concepts", 0, 2003, 1],
  ["Visish Srinivasan", "Computer Concepts", 0, 2003, 10],
  ["Zachary Landes", "Computer Concepts", 0, 2003, 9],
  ["Lunani Yen", "Creed", 0, 2003, 4],
  ["Corey Reese", "Economics", 0, 2003, 3],
  ["Sherrie Song", "Economics", 0, 2003, 4],
  [
    "Vivian Chen",
    "Bhavna Muthangi",
    "Corey Reese",
    "Entrepreneurship",
    0,
    2003,
    1,
  ],
  ["Helen Wu", "FBLA Principles and Procedures", 0, 2003, 4],
  ["Jackie Laird", "FBLA Principles and Procedures", 0, 2003, 3],
  ["Jennifer Sheu", "FBLA Principles and Procedures", 0, 2003, 1],
  ["Serena Mau", "FBLA Principles and Procedures", 0, 2003, 6],
  ["Clarence Yung", "Future Business Leader", 0, 2003, 1],
  ["Ani Goranova", "Introduction to Business", 0, 2003, 7],
  ["Boyuan Zhu", "Introduction to Business", 0, 2003, 2],
  ["Cory O'Yang", "Introduction to Business", 0, 2003, 3],
  ["Kim Luong", "Introduction to Business", 0, 2003, 1],
  ["Meena Siddiqui", "Introduction to Business", 0, 2003, 8],
  ["Serena Mau", "Introduction to Business", 0, 2003, 5],
  ["Aditi Goel", "Introduction to Business Communication", 0, 2003, 9],
  ["Carol Wong", "Introduction to Business Communication", 0, 2003, 6],
  ["Jule Tran", "Introduction to Business Communication", 0, 2003, 1],
  ["Roger Tjhia", "Introduction to Business Communication", 0, 2003, 10],
  ["Sadaf Shahsahebi", "Job Interview", 0, 2003, 1],
  ["Andrea Lam", "Marketing", 0, 2003, 3],
  ["Angela Contreras", "Marketing", 0, 2003, 7],
  ["Bhavna Muthangi", "Marketing", 0, 2003, 2],
  ["Clarence Yung", "Marketing", 0, 2003, 1],
  ["Janette Wong", "Marketing", 0, 2003, 8],
  ["Laurence Jiang", "Marketing", 0, 2003, 10],
  ["Aditi Goel", "Public Speaking I", 0, 2003, 2],
  ["Scott Graves", "Public Speaking II", 0, 2003, 4],
  ["Brian Wiebe", "Technology Concepts", 0, 2003, 2],
  ["Scott Ichikawa", "Technology Concepts", 0, 2003, 7],
  ["Visish Srinivasan", "Technology Concepts", 0, 2003, 9],
  ["Alan Chang", "Visual Basic Programming", 0, 2003, 6],
  ["Scott Ichikawa", "Visual Basic Programming", 0, 2003, 4],
  ["Shahin Saneinejad", "Visual Basic Programming", 0, 2003, 3],
  ["Xavier Gaeta", "Visual Basic Programming", 0, 2003, 2],
  ["Kelly Kato", "Word Processing I", 0, 2003, 8],
  ["Lunani Yen", "Word Processing I", 0, 2003, 9],
  ["Michael Hsu", "Word Processing II", 0, 2003, 9],
  ["Phillip Tao", "Word Processing II", 0, 2003, 3],
  ["Sadaf Shahsahebi", "Word Processing II", 0, 2003, 2],
  [
    "Katherine Lao",
    "Janette Wong",
    "Rossini Yen",
    "American Enterprise",
    2,
    2002,
    5,
  ],
  ["Kevin Lin", "Business Calculations", 2, 2002, 3],
  ["Andrea Lam", "Business Law", 2, 2002, 2],
  ["Nami Kasuya", "Business Law", 2, 2002, 4],
  ["Laurence Jiang", "Business Math", 2, 2002, 5],
  ["Elham Mireshghi", "Michael Sheppard", "Business Plan", 2, 2002, 2],
  ["Bhavna Muthangi", "Introduction to Business", 2, 2002, 1],
  ["Corey Reese", "Marketing", 2, 2002, 3],
  [
    "Zachary Landes",
    "Jo Lin",
    "Corey Reese",
    "Partnership with Business",
    2,
    2002,
    5,
  ],
  ["Jennifer Kim", "Accounting I", 1, 2002, 9],
  ["John Bereznak", "Accounting I", 1, 2002, 2],
  ["Allison Brown", "Accounting II", 1, 2002, 3],
  ["Angel Chao", "Accounting II", 1, 2002, 2],
  ["John Bereznak", "Accounting II", 1, 2002, 7],
  ["Marina Sheu", "Accounting II", 1, 2002, 5],
  [
    "Katherine Lao",
    "Janette Wong",
    "Rossini Yen",
    "American Enterprise",
    1,
    2002,
    1,
  ],
  ["Laurence Jiang", "Banking and Financial Systems", 1, 2002, 1],
  ["Sherrie Song", "Banking and Financial Systems", 1, 2002, 4],
  ["Kevin Lin", "Business Calculations", 1, 2002, 1],
  ["Andrea Lam", "Business Law", 1, 2002, 3],
  ["Daniel Wright", "Business Law", 1, 2002, 8],
  ["David Wright", "Business Law", 1, 2002, 4],
  ["Grace Luo", "Business Law", 1, 2002, 1],
  ["Kevin Lin", "Business Law", 1, 2002, 5],
  ["Nami Kasuya", "Business Law", 1, 2002, 2],
  ["Bhavna Muthangi", "Business Math", 1, 2002, 1],
  ["Laurence Jiang", "Business Math", 1, 2002, 2],
  ["Elham Mireshghi", "Michael Sheppard", "Business Plan", 1, 2002, 3],
  ["Cindy Yee", "Business Procedures", 1, 2002, 9],
  ["Jeff Chen", "Business Procedures", 1, 2002, 3],
  ["Jo Lin", "Business Procedures", 1, 2002, 4],
  [
    "Nami Kasuya",
    "Bhavna Muthangi",
    "Sadaf Shahsahebi",
    "Community Service",
    1,
    2002,
    3,
  ],
  ["Gautam Raj", "Computer Concepts", 1, 2002, 1],
  ["Angela Contreras", "Creed", 1, 2002, 5],
  ["Angel Chao", "Jo Lin", "Grace Luo", "Dr. Jessie Graham Award", 1, 2002, -1],
  [
    "Sabah Khan",
    "Thomas Ni",
    "Albert Yen",
    "Emerging Business Issues",
    1,
    2002,
    2,
  ],
  [
    "Vivian Chen",
    "Kevin Nguyen",
    "Corey Reese",
    "Entrepreneurship",
    1,
    2002,
    5,
  ],
  ["Laura Kuo", "FBLA Principles and Procedures", 1, 2002, 2],
  ["Serena Mau", "FBLA Principles and Procedures", 1, 2002, 7],
  ["Clarence Yung", "Future Business Leader", 1, 2002, 3],
  ["Lillian Lee", "Impromptu Speaking", 1, 2002, 6],
  ["Angela Contreras", "International Business", 1, 2002, 2],
  ["Clarence Yung", "International Business", 1, 2002, 3],
  ["Bhavna Muthangi", "Introduction to Business", 1, 2002, 1],
  ["Boyuan Zhu", "Introduction to Business", 1, 2002, 4],
  ["Cory O'Yang", "Introduction to Business", 1, 2002, 7],
  ["Kim Luong", "Introduction to Business", 1, 2002, 5],
  ["Scott Graves", "Introduction to Business", 1, 2002, 6],
  ["Derrick Tang", "Introduction to Business Communication", 1, 2002, 5],
  ["Cindy O'Yang", "Job Interview", 1, 2002, 7],
  [
    "Grace Luo",
    "Clarence Yung",
    "Local Chapter Annual Business Report",
    1,
    2002,
    4,
  ],
  ["Corey Reese", "Marketing", 1, 2002, 1],
  ["Janette Wong", "Marketing", 1, 2002, 6],
  ["Zachary Landes", "Marketing", 1, 2002, 5],
  [
    "Zachary Landes",
    "Jo Lin",
    "Corey Reese",
    "Partnership with Business",
    1,
    2002,
    1,
  ],
  ["Aditi Goel", "Public Speaking I", 1, 2002, 3],
  ["Homestead", "Sweepstakes", 1, 2002, 1],
  ["Gautam Raj", "Technology Concepts", 1, 2002, 1],
  ["Sadaf Shahsahebi", "Word Processing II", 1, 2002, 9],
  ["Daisy Tran", "Accounting I", 0, 2002, 3],
  ["Debbie Yip", "Accounting I", 0, 2002, 5],
  ["Jennifer Kim", "Accounting I", 0, 2002, 4],
  ["John Bereznak", "Accounting I", 0, 2002, 1],
  ["Allison Brown", "Accounting II", 0, 2002, 2],
  ["Angel Chao", "Accounting II", 0, 2002, 1],
  ["Debbie Yip", "Accounting II", 0, 2002, 4],
  ["John Bereznak", "Accounting II", 0, 2002, 5],
  ["Kevin Nguyen", "Accounting II", 0, 2002, 6],
  ["Marina Sheu", "Accounting II", 0, 2002, 3],
  ["Alan Chang", "Business Calculations", 0, 2002, 7],
  ["Kevin Lin", "Business Calculations", 0, 2002, 9],
  ["Youming Yang", "Business Calculations", 0, 2002, 8],
  ["Meera Seshadri", "Business Communication", 0, 2002, 10],
  ["Andrea Lam", "Business Law", 0, 2002, 5],
  ["Daniel Wright", "Business Law", 0, 2002, 6],
  ["David Wright", "Business Law", 0, 2002, 2],
  ["Grace Luo", "Business Law", 0, 2002, 4],
  ["Kevin Lin", "Business Law", 0, 2002, 1],
  ["Nami Kasuya", "Business Law", 0, 2002, 3],
  ["Bhavna Muthangi", "Business Math", 0, 2002, 2],
  ["Kamil Brozek", "Business Math", 0, 2002, 10],
  ["Laurence Jiang", "Business Math", 0, 2002, 1],
  ["Qian Chen", "Business Math", 0, 2002, 9],
  ["Cindy Yee", "Business Procedures", 0, 2002, 4],
  ["Jeff Chen", "Business Procedures", 0, 2002, 3],
  ["Jo Lin", "Business Procedures", 0, 2002, 2],
  ["Marina Sheu", "Business Procedures", 0, 2002, 9],
  ["Vivian Chen", "Business Procedures", 0, 2002, 8],
  ["Alan Lee", "Computer Concepts", 0, 2002, 10],
  ["Dang Nguyen", "Computer Concepts", 0, 2002, 6],
  ["Gautam Raj", "Computer Concepts", 0, 2002, 2],
  ["Gerald Wong", "Computer Concepts", 0, 2002, 1],
  ["Angela Contreras", "Creed", 0, 2002, 1],
  ["Angel Chao", "Economics", 0, 2002, 5],
  [
    "Vivian Chen",
    "Kevin Nguyen",
    "Corey Reese",
    "Entrepreneurship",
    0,
    2002,
    2,
  ],
  ["AJ Lee", "FBLA Principles and Procedures", 0, 2002, 7],
  ["Jo Lin", "FBLA Principles and Procedures", 0, 2002, 3],
  ["Kate Wang", "FBLA Principles and Procedures", 0, 2002, 9],
  ["Laura Kuo", "FBLA Principles and Procedures", 0, 2002, 1],
  ["Serena Mau", "FBLA Principles and Procedures", 0, 2002, 2],
  ["Clarence Yung", "Future Business Leader", 0, 2002, 2],
  ["Sabah Khan", "Future Business Leader", 0, 2002, 3],
  ["Bhavna Muthangi", "Introduction to Business", 0, 2002, 1],
  ["Boyuan Zhu", "Introduction to Business", 0, 2002, 2],
  ["Cory O'Yang", "Introduction to Business", 0, 2002, 8],
  ["Kim Luong", "Introduction to Business", 0, 2002, 4],
  ["Scott Graves", "Introduction to Business", 0, 2002, 6],
  ["Derrick Tang", "Introduction to Business Communication", 0, 2002, 5],
  ["Jackie Laird", "Introduction to Business Communication", 0, 2002, 6],
  ["Jennifer Sheu", "Introduction to Business Communication", 0, 2002, 8],
  ["Cindy O'Yang", "Job Interview", 0, 2002, 1],
  ["Angela Contreras", "Marketing", 0, 2002, 8],
  ["Corey Reese", "Marketing", 0, 2002, 1],
  ["Elham Mireshghi", "Marketing", 0, 2002, 9],
  ["Janette Wong", "Marketing", 0, 2002, 6],
  ["Jessica Yen", "Marketing", 0, 2002, 5],
  ["Zachary Landes", "Marketing", 0, 2002, 3],
  ["Aditi Goel", "Public Speaking I", 0, 2002, 1],
  ["Aparna Goel", "Public Speaking II", 0, 2002, 3],
  ["Albert Yen", "Technology Concepts", 0, 2002, 10],
  ["Carl Cheng", "Technology Concepts", 0, 2002, 6],
  ["Gautam Raj", "Technology Concepts", 0, 2002, 1],
  ["Linda Truong", "Technology Concepts", 0, 2002, 9],
  ["Lauren Wong", "Word Processing I", 0, 2002, 4],
  ["Phillip Tao", "Word Processing I", 0, 2002, 5],
  ["Darlene Franklin", "Word Processing II", 0, 2002, 1],
  ["Sadaf Shahsahebi", "Word Processing II", 0, 2002, 3],
  ["Sandra Matsumoto", "Word Processing II", 0, 2002, 2],
  ["Jonathan Chong", "Accounting II", 2, 2001, 8],
  [
    "Meera Seshadri",
    "Sabah Khan",
    "Tara Friedrich",
    "American Enterprise",
    2,
    2001,
    3,
  ],
  ["Marni Landes", "Business Communication", 2, 2001, 1],
  ["Michael Lew", "Business Law", 2, 2001, 1],
  ["Clarence Yung", "Business Math", 2, 2001, 1],
  [
    "Aparna Goel",
    "Cindy O'Yang",
    "Tasha Matharu",
    "Community Service",
    2,
    2001,
    4,
  ],
  ["Michael Lew", "Insurance Operations (Open Event)", 2, 2001, 2],
  ["Christina Young", "International Business", 2, 2001, 6],
  ["Bhavna Muthangi", "Introduction to Business Communication", 2, 2001, 3],
  ["Zachary Landes", "Introduction to Business Communication", 2, 2001, 5],
  ["Sabah Khan", "Job Interview", 2, 2001, 6],
  ["Evan Gates", "Marketing", 2, 2001, 6],
  ["Allison Brown", "Accounting I", 1, 2001, 3],
  ["Angel Chao", "Accounting I", 1, 2001, 1],
  ["Chia-Hui Lin", "Accounting I", 1, 2001, 4],
  ["Jonathan Chong", "Accounting II", 1, 2001, 2],
  ["Nancy Lin", "Accounting II", 1, 2001, 1],
  [
    "Meera Seshadri",
    "Sabah Khan",
    "Michael Huang",
    "American Enterprise",
    1,
    2001,
    1,
  ],
  ["Kevin Lin", "Business Calculations", 1, 2001, 7],
  ["Marni Landes", "Business Communication", 1, 2001, 4],
  ["Anne LaRue", "Business Law", 1, 2001, 4],
  ["Corey Reese", "Business Law", 1, 2001, 1],
  ["David Wright", "Business Law", 1, 2001, 3],
  ["Michael Lew", "Business Law", 1, 2001, 2],
  ["Nami Kasuya", "Business Law", 1, 2001, 7],
  ["Clarence Yung", "Business Math", 1, 2001, 2],
  ["Nick Lee", "Business Math", 1, 2001, 1],
  ["Michael Lew", "Aparna Goel", "Business Plan", 1, 2001, 3],
  ["Conrad Chan", "Business Procedures", 1, 2001, 4],
  ["Michael Lee", "Business Procedures", 1, 2001, 2],
  ["Clarence Yung", "Chapter Website", 1, 2001, 9],
  [
    "Aparna Goel",
    "Cindy O'Yang",
    "Tasha Matharu",
    "Community Service",
    1,
    2001,
    1,
  ],
  ["Jeff Day", "Computer Concepts", 1, 2001, 4],
  ["Stephanie Tang", "Economics", 1, 2001, 8],
  [
    "Jonathan Laird",
    "Kevin Yung",
    "Lauren Jackson",
    "Emerging Business Issues",
    1,
    2001,
    6,
  ],
  ["Corey Reese", "Raj Kumar", "Kevin Nguyen", "Entrepreneurship", 1, 2001, 2],
  ["Alan Chang", "FBLA Principles and Procedures", 1, 2001, 3],
  ["Vivian Chen", "FBLA Principles and Procedures", 1, 2001, 5],
  ["Christina Young", "International Business", 1, 2001, 1],
  ["Janette Wong", "International Business", 1, 2001, 7],
  ["Bhavna Muthangi", "Introduction to Business", 1, 2001, 1],
  ["Grace Luo", "Introduction to Business", 1, 2001, 10],
  ["Jessica Yen", "Introduction to Business", 1, 2001, 5],
  ["Zachary Landes", "Introduction to Business", 1, 2001, 2],
  ["Bhavna Muthangi", "Introduction to Business Communication", 1, 2001, 1],
  ["Clarence Yung", "Introduction to Business Communication", 1, 2001, 5],
  ["Sadaf Shahsahebi", "Introduction to Business Communication", 1, 2001, 7],
  ["Sabah Khan", "Job Interview", 1, 2001, 1],
  ["Jonathan Chong", "Local Chapter Annual Business Report", 1, 2001, 6],
  ["Evan Gates", "Marketing", 1, 2001, 1],
  ["Rossini Yen", "Marketing", 1, 2001, 10],
  [
    "Alan Chang",
    "Henry Tse",
    "Alan Lee",
    "Multimedia Presentation",
    1,
    2001,
    6,
  ],
  [
    "David Wright",
    "Corey Reese",
    "Gerald Wong",
    "Partnership with Business",
    1,
    2001,
    4,
  ],
  ["Aparna Goel", "Public Speaking I", 1, 2001, 1],
  ["Homestead", "Sweepstakes", 1, 2001, 1],
  ["Allison Brown", "Accounting I", 0, 2001, 1],
  ["Angel Chao", "Accounting I", 0, 2001, 2],
  ["Chia-Hui Lin", "Accounting I", 0, 2001, 3],
  ["Christina Young", "Accounting I", 0, 2001, 8],
  ["Lan Nguyen", "Accounting I", 0, 2001, 9],
  ["Sherrie Song", "Accounting I", 0, 2001, 7],
  ["Allison Brown", "Accounting II", 0, 2001, 4],
  ["Angel Chao", "Accounting II", 0, 2001, 3],
  ["Jonathan Chong", "Accounting II", 0, 2001, 1],
  ["Nancy Lin", "Accounting II", 0, 2001, 2],
  ["Sherrie Song", "Accounting II", 0, 2001, 5],
  ["Bor-Shiu Chow", "Business Calculations", 0, 2001, 3],
  ["Evan Gates", "Business Calculations", 0, 2001, 9],
  ["Kevin Lin", "Business Calculations", 0, 2001, 1],
  ["Youming Yang", "Business Calculations", 0, 2001, 4],
  ["Helen Liou", "Business Communication", 0, 2001, 4],
  ["Marni Landes", "Business Communication", 0, 2001, 1],
  ["Meera Seshadri", "Business Communication", 0, 2001, 9],
  ["Anne LaRue", "Business Law", 0, 2001, 2],
  ["Corey Reese", "Business Law", 0, 2001, 5],
  ["David Wright", "Business Law", 0, 2001, 3],
  ["Michael Lew", "Business Law", 0, 2001, 1],
  ["Nami Kasuya", "Business Law", 0, 2001, 4],
  ["William Chow", "Business Law", 0, 2001, 6],
  ["Alan Chang", "Business Math", 0, 2001, 9],
  ["Clarence Yung", "Business Math", 0, 2001, 5],
  ["Grace Luo", "Business Math", 0, 2001, 10],
  ["Nick Lee", "Business Math", 0, 2001, 4],
  ["Conrad Chan", "Business Procedures", 0, 2001, 5],
  ["Marina Sheu", "Business Procedures", 0, 2001, 6],
  ["Michael Lee", "Business Procedures", 0, 2001, 2],
  ["Candice Lee", "Computer Applications", 0, 2001, 7],
  ["Jonathan Laird", "Computer Applications", 0, 2001, 2],
  ["Vivian Zhang", "Computer Applications", 0, 2001, 6],
  ["Gerald Wong", "Computer Concepts", 0, 2001, 5],
  ["Jeff Day", "Computer Concepts", 0, 2001, 1],
  ["William Lee", "Computer Concepts", 0, 2001, 4],
  ["Karen Yei", "Creed", 0, 2001, 4],
  ["Amy Ren", "Economics", 0, 2001, 4],
  ["Stephanie Tang", "Economics", 0, 2001, 1],
  ["Raj Kumar", "Kevin Nguyen", "Corey Reese", "Entrepreneurship", 0, 2001, 1],
  ["Dewey Huang", "Future Business Leader", 0, 2001, 7],
  ["Kevin Nguyen", "Future Business Leader", 0, 2001, 6],
  ["Bhavna Muthangi", "Introduction to Business", 0, 2001, 1],
  ["Grace Luo", "Introduction to Business", 0, 2001, 5],
  ["Janette Wong", "Introduction to Business", 0, 2001, 10],
  ["Jessica Yen", "Introduction to Business", 0, 2001, 3],
  ["Zachary Landes", "Introduction to Business", 0, 2001, 2],
  ["Bhavna Muthangi", "Introduction to Business Communication", 0, 2001, 1],
  ["Clarence Yung", "Introduction to Business Communication", 0, 2001, 2],
  ["Sadaf Shahsahebi", "Introduction to Business Communication", 0, 2001, 5],
  ["Jessica Yen", "Introduction to Business Communication", 0, 2001, 9],
  ["Katherine Lao", "Introduction to Business Communication", 0, 2001, 6],
  ["Sabah Khan", "Job Interview", 0, 2001, 3],
  ["Tasha Matharu", "Public Speaking", 0, 2001, 5],
  ["Aparna Goel", "Public Speaking I", 0, 2001, 1],
  ["Gautam Raj", "Technology Concepts", 0, 2001, 7],
  ["Kevin Yung", "Technology Concepts", 0, 2001, 5],
  ["Vivian Chong", "Technology Concepts", 0, 2001, 6],
  ["William Lee", "Technology Concepts", 0, 2001, 9],
  ["Helen Liou", "Word Processing I", 0, 2001, 10],
  ["Sandy Liou", "Word Processing I", 0, 2001, 8],
  ["Darlene Franklin", "Word Processing II", 0, 2001, 3],
  ["Tiffany Kim", "Word Processing II", 0, 2001, 1],
  ["Vivian Chen", "Word Processing II", 0, 2001, 6],
  ["Jonathan Chong", "Accounting I", 2, 2000, 3],
  ["Nancy Lin", "Accounting I", 2, 2000, 4],
  ["Jennifer Yen", "Accounting II", 2, 2000, 6],
  ["Stephanie Yang", "Business Communication", 2, 2000, 6],
  ["Angel Chao", "Business Law", 2, 2000, 1],
  ["Christina Young", "Business Law", 2, 2000, 2],
  ["Nicholas Chang", "Mikhail Voroniouk", "Business Plan", 2, 2000, 2],
  ["Jessica Yen", "FBLA Principles and Procedures", 2, 2000, 8],
  ["Mia Chiu", "Marketing", 2, 2000, 4],
  ["Jonathan Chong", "Accounting I", 1, 2000, 2],
  ["Nancy Lin", "Accounting I", 1, 2000, 1],
  ["Nora Go", "Accounting I", 1, 2000, 7],
  ["Brian Schwartz", "Accounting II", 1, 2000, 5],
  ["Jennifer Yen", "Accounting II", 1, 2000, 2],
  ["Nancy Lin", "Accounting II", 1, 2000, 6],
  ["Steve Chae", "Accounting II", 1, 2000, 3],
  ["Meera Seshadri", "American Enterprise", 1, 2000, 2],
  ["Stephanie Yang", "Business Communication", 1, 2000, 1],
  ["Xijia Chen", "Business Communication", 1, 2000, 5],
  ["Angel Chao", "Business Law", 1, 2000, 1],
  ["Anne LaRue", "Business Law", 1, 2000, 5],
  ["Christina Young", "Business Law", 1, 2000, 2],
  ["David Wright", "Business Law", 1, 2000, 3],
  ["Michael Lew", "Business Law", 1, 2000, 4],
  ["Jonathan Lowd", "Business Math", 1, 2000, 5],
  ["Kevin Lin", "Business Math", 1, 2000, 6],
  ["Nicholas Chang", "Mikhail Voroniouk", "Business Plan", 1, 2000, 1],
  ["Michael Lee", "Business Procedures", 1, 2000, 5],
  ["Clarence Yung", "Chapter Website", 1, 2000, 8],
  ["Aparna Goel", "Cindy O'Yang", "Community Service", 1, 2000, 4],
  ["Vivian Chong", "Computer Concepts", 1, 2000, 9],
  ["Aparna Goel", "Creed", 1, 2000, 2],
  ["Homestead", "Emerging Business Issues", 1, 2000, 6],
  [
    "Jennifer Chao",
    "Jonathan Chong",
    "Jennifer Yen",
    "Entrepreneurship",
    1,
    2000,
    2,
  ],
  ["Angel Chao", "FBLA Principles and Procedures", 1, 2000, 3],
  ["Jessica Yen", "FBLA Principles and Procedures", 1, 2000, 2],
  ["Mia Chiu", "Future Business Leader", 1, 2000, 9],
  ["Brian Daner", "Impromptu Speaking", 1, 2000, 1],
  ["Christina Young", "International Business", 1, 2000, 5],
  ["Michael Lew", "International Business", 1, 2000, 1],
  ["Clarence Yung", "Introduction to Business", 1, 2000, 1],
  ["Jessica Yen", "Introduction to Business", 1, 2000, 5],
  ["Sabah Khan", "Introduction to Business", 1, 2000, 9],
  ["David Wright", "Introduction to Business Communication", 1, 2000, 9],
  ["Marina Sheu", "Introduction to Parliamentary Procedure", 1, 2000, 6],
  ["Nami Kassuyn", "Introduction to Parliamentary Procedure", 1, 2000, 5],
  ["Michael Wong", "Job Description Manual", 1, 2000, 2],
  ["Nora Go", "Job Interview", 1, 2000, 8],
  ["Jonathan Chong", "Local Chapter Annual Business Report", 1, 2000, 7],
  ["Cindy O'Yang", "Machine Transcription", 1, 2000, 9],
  ["Rossini Yen", "Machine Transcription", 1, 2000, 6],
  ["Mia Chiu", "Marketing", 1, 2000, 1],
  ["Samuel Lee", "Marketing", 1, 2000, 4],
  [
    "Samuel Lee",
    "Michael Wong",
    "Mikhail Voroniouk",
    "Partnership with Business",
    1,
    2000,
    1,
  ],
  ["Jennifer Chao", "Scholarship", 1, 2000, -2],
  ["Jennifer Yen", "Scholarship", 1, 2000, -2],
  ["Steve Chae", "Scholarship", 1, 2000, -2],
  ["Homestead", "Sweepstakes", 1, 2000, 1],
  ["John Chen", "Accounting I", 0, 2000, 8],
  ["Jonathan Chong", "Accounting I", 0, 2000, 1],
  ["Lan Nguyen", "Accounting I", 0, 2000, 7],
  ["Nancy Lin", "Accounting I", 0, 2000, 2],
  ["Nora Go", "Accounting I", 0, 2000, 4],
  ["Sabrina Sanchez", "Accounting I", 0, 2000, 3],
  ["Brian Schwartz", "Accounting II", 0, 2000, 2],
  ["Jennifer Yen", "Accounting II", 0, 2000, 1],
  ["Nancy Lin", "Accounting II", 0, 2000, 4],
  ["Steve Chae", "Accounting II", 0, 2000, 3],
  ["Bor-Shiu Chow", "Business Calculations", 0, 2000, 8],
  ["Michael Wong", "Business Calculations", 0, 2000, 7],
  ["Yanting Li", "Business Calculations", 0, 2000, 6],
  ["Marni Landes", "Business Communication", 0, 2000, 5],
  ["Stephanie Tang", "Business Communication", 0, 2000, 2],
  ["Xijia Chen", "Business Communication", 0, 2000, 6],
  ["Angel Chao", "Business Law", 0, 2000, 1],
  ["Anne LaRue", "Business Law", 0, 2000, 3],
  ["Christina Young", "Business Law", 0, 2000, 2],
  ["David Wright", "Business Law", 0, 2000, 5],
  ["Michael Lew", "Business Law", 0, 2000, 4],
  ["Mikhail Voroniouk", "Business Law", 0, 2000, 7],
  ["Clarence Yung", "Business Math", 0, 2000, 8],
  ["Jonathan Lowd", "Business Math", 0, 2000, 1],
  ["Kevin Lin", "Business Math", 0, 2000, 5],
  ["Amy Ren", "Business Procedures", 0, 2000, 8],
  ["Marie Levey", "Business Procedures", 0, 2000, 7],
  ["Michael Lee", "Business Procedures", 0, 2000, 1],
  ["Michael Lew", "Business Procedures", 0, 2000, 4],
  ["Jonathan Laird", "Computer Applications", 0, 2000, 5],
  ["Shruthi Koundinya", "Computer Applications", 0, 2000, 10],
  ["Vivian Zhang", "Computer Applications", 0, 2000, 7],
  ["Daniel Blinick", "Computer Concepts", 0, 2000, 5],
  ["Jeff Day", "Computer Concepts", 0, 2000, 2],
  ["Vivian Chong", "Computer Concepts", 0, 2000, 6],
  ["Aparna Goel", "Creed", 0, 2000, 1],
  ["Brian Schwartz", "Economics", 0, 2000, 3],
  ["Daniel Blinick", "Economics", 0, 2000, 5],
  ["Jennifer Chao", "Economics", 0, 2000, 6],
  ["Mia Chiu", "Economics", 0, 2000, 7],
  [
    "Jennifer Chao",
    "Jonathan Chong",
    "Jennifer Yen",
    "Entrepreneurship",
    0,
    2000,
    1,
  ],
  ["Mia Chiu", "Future Business Leader", 0, 2000, 2],
  ["Roger Yei", "Future Business Leader", 0, 2000, 5],
  ["Clarence Yung", "Introduction to Business", 0, 2000, 5],
  ["Jessica Yen", "Introduction to Business", 0, 2000, 6],
  ["Kevin Lin", "Introduction to Business", 0, 2000, 8],
  ["Sabah Khan", "Introduction to Business", 0, 2000, 3],
  ["Aparna Goel", "Introduction to Business Communication", 0, 2000, 5],
  ["Candice Lee", "Introduction to Business Communication", 0, 2000, 10],
  ["David Wright", "Introduction to Business Communication", 0, 2000, 2],
  ["Jessica Yen", "Introduction to Business Communication", 0, 2000, 9],
  ["Meera Seshadri", "Introduction to Business Communication", 0, 2000, 4],
  ["Nora Go", "Job Interview", 0, 2000, 2],
  ["Wayne Chang", "Public Speaking", 0, 2000, 1],
  ["Rory Loeb", "Technology Concepts", 0, 2000, 9],
  ["William Lee", "Technology Concepts", 0, 2000, 8],
  ["Sadaf Shahsahebi", "Word Processing I", 0, 2000, 8],
  ["Sandy Liou", "Word Processing I", 0, 2000, 5],
  ["Tiffany Lim", "Word Processing I", 0, 2000, 3],
  ["Darlene Franklin", "Word Processing II", 0, 2000, 2],
  ["Elizabeth Wright", "Word Processing II", 0, 2000, 3],
  ["Serena Kuo", "Word Processing II", 0, 2000, 4],
  ["Connie Young", "Accounting I", 2, 1999, 7],
  ["Vickie Chiang", "Accounting I", 2, 1999, 8],
  ["Lee Pang", "Accounting II", 2, 1999, 2],
  [
    "Steve Chae",
    "Rahul Mehta",
    "Lan Nguyen",
    "American Enterprise",
    2,
    1999,
    2,
  ],
  ["Jennifer Yen", "Business Law", 2, 1999, 5],
  ["Sam Lee", "International Business", 2, 1999, 3],
  ["Jonathan Chong", "Introduction to Business", 2, 1999, 4],
  ["Michael Lew", "Introduction to Business", 2, 1999, 6],
  ["Angel Chao", "Introduction to Business Communication", 2, 1999, 5],
  ["Marni Landes", "Introduction to Business Communication", 2, 1999, 9],
  ["Garrett Kuramoto", "Mr. FBL", 2, 1999, 3],
  ["Garrett Kuramoto", "State Annual Report", 2, 1999, 2],
  ["Grace Park", "$1000 Scholarship", 1, 1999, -2],
  ["Connie Young", "Accounting I", 1, 1999, 3],
  ["Jennifer Lui", "Accounting I", 1, 1999, 9],
  ["Jennifer Yen", "Accounting I", 1, 1999, 2],
  ["Vickie Chiang", "Accounting I", 1, 1999, 1],
  ["Brian Schwartz", "Accounting II", 1, 1999, 8],
  ["Lee Pang", "Accounting II", 1, 1999, 1],
  [
    "Steve Chae",
    "Rahul Mehta",
    "Lan Nguyen",
    "American Enterprise",
    1,
    1999,
    2,
  ],
  ["Lee Pang", "Business Calculations", 1, 1999, 3],
  ["Liz Wright", "Business Communication", 1, 1999, 4],
  ["Aileen Chan", "Business Law", 1, 1999, 2],
  ["Christina Young", "Business Law", 1, 1999, 3],
  ["Jennifer Yen", "Business Law", 1, 1999, 1],
  ["Laura Phan", "Business Law", 1, 1999, 4],
  ["Kristina Trinh", "Grace Park", "Liz Wright", "Business Plan", 1, 1999, 1],
  ["Michael Wong", "Chapter Website", 1, 1999, 4],
  ["Nora Go", "Diana Keh", "Alice Tang", "Community Service", 1, 1999, 3],
  ["Daniel Blinick", "Computer Concepts", 1, 1999, 8],
  ["Wayne Chang", "Creed", 1, 1999, 2],
  ["Patricia Liu", "FBLA Principles and Procedures", 1, 1999, 1],
  ["Wayne Chang", "FBLA Principles and Procedures", 1, 1999, 8],
  ["Andy Chen", "Impromptu Speaking", 1, 1999, 5],
  ["David Wright", "International Business", 1, 1999, 4],
  ["Sam Lee", "International Business", 1, 1999, 1],
  ["Jonathan Chong", "Introduction to Business", 1, 1999, 1],
  ["Michael Lew", "Introduction to Business", 1, 1999, 2],
  ["Stephanie Tang", "Introduction to Business", 1, 1999, 5],
  ["Angel Chao", "Introduction to Business Communication", 1, 1999, 2],
  ["Jonathan Chong", "Introduction to Business Communication", 1, 1999, 3],
  ["Marni Landes", "Introduction to Business Communication", 1, 1999, 1],
  ["Sabah Khan", "Introduction to Parliamentary Procedure", 1, 1999, 7],
  ["Tasha Matharu", "Introduction to Parliamentary Procedure", 1, 1999, 2],
  ["Michael Wong", "Job Description Manual", 1, 1999, 4],
  ["Daniel Blinick", "Marketing", 1, 1999, 3],
  ["Mia Chiu", "Marketing", 1, 1999, 4],
  ["Garrett Kuramoto", "Mr. FBL", 1, 1999, 1],
  ["Michael Chen", "Public Speaking", 1, 1999, 2],
  ["Homestead", "Sweepstakes", 1, 1999, 1],
  ["Jennifer Lui", "Word Processing", 1, 1999, 10],
  ["Connie Young", "Accounting I", 0, 1999, 2],
  ["David Kempe", "Accounting I", 0, 1999, 7],
  ["Jennifer Lui", "Accounting I", 0, 1999, 5],
  ["Jennifer Yen", "Accounting I", 0, 1999, 1],
  ["Kurtis Kludt", "Accounting I", 0, 1999, 10],
  ["Vickie Chang", "Accounting I", 0, 1999, 3],
  ["Brian Schwartz", "Accounting II", 0, 1999, 5],
  ["Cindy Kodani", "Accounting II", 0, 1999, 4],
  ["Garrett Kuramoto", "Accounting II", 0, 1999, 7],
  ["Lee Pang", "Accounting II", 0, 1999, 1],
  ["Ellen Chang", "Business Calculations", 0, 1999, 5],
  ["Lee Pang", "Business Calculations", 0, 1999, 1],
  ["Michael Wong", "Business Calculations", 0, 1999, 7],
  ["Xijia Chen", "Business Calculations", 0, 1999, 8],
  ["Brian Daner", "Business Communication", 0, 1999, 3],
  ["Grace Park", "Business Communication", 0, 1999, 10],
  ["Liz Wright", "Business Communication", 0, 1999, 1],
  ["Nora Go", "Business Communication", 0, 1999, 7],
  ["Aileen Chan", "Business Law", 0, 1999, 3],
  ["Christina Young", "Business Law", 0, 1999, 2],
  ["Jennifer Yen", "Business Law", 0, 1999, 1],
  ["Laura Phan", "Business Law", 0, 1999, 4],
  ["Mariann Hu", "Business Law", 0, 1999, 5],
  ["Mikhail Voroniouk", "Business Law", 0, 1999, 10],
  ["Bor-Shiu Chow", "Business Math", 0, 1999, 9],
  ["Tina Hsieh", "Business Math", 0, 1999, 5],
  ["Aileen Chan", "Business Procedures", 0, 1999, 6],
  ["Edward Hsu", "Business Procedures", 0, 1999, 10],
  ["Cindy Kodani", "Computer Applications", 0, 1999, 6],
  ["David Huang", "Computer Applications", 0, 1999, 1],
  ["Daniel Blinick", "Computer Concepts", 0, 1999, 4],
  ["David Huang", "Computer Concepts", 0, 1999, 8],
  ["Wayne Chang", "Creed", 0, 1999, 1],
  ["Andy Chen", "Economics", 0, 1999, 9],
  ["Mia Chiu", "Economics", 0, 1999, 10],
  [
    "Kristina Trinh",
    "Jennifer Chao",
    "Jenny Kim",
    "Entrepreneurship",
    0,
    1999,
    2,
  ],
  ["Jenny Liu", "Information Processing Concepts", 0, 1999, 7],
  ["Rory Loeb", "Information Processing Concepts", 0, 1999, 9],
  ["Jonathan Chong", "Introduction to Business", 0, 1999, 1],
  ["Michael Lew", "Introduction to Business", 0, 1999, 2],
  ["Sabah Khan", "Introduction to Business", 0, 1999, 10],
  ["Stephanie Yang", "Introduction to Business", 0, 1999, 5],
  ["Angel Chao", "Introduction to Business Communication", 0, 1999, 2],
  ["Jonathan Chong", "Introduction to Business Communication", 0, 1999, 4],
  ["Marni Landes", "Introduction to Business Communication", 0, 1999, 3],
  ["Patricia Liu", "Introduction to Business Communication", 0, 1999, 8],
  ["Nora Go", "Job Interview", 0, 1999, 2],
  ["James Hong", "Keyboarding Applications", 0, 1999, 1],
  ["Masumi Watanabe", "Keyboarding Applications", 0, 1999, 7],
  ["Garrett Kuramoto", "Mr. FBL", 0, 1999, 1],
  ["Grace Park", "Ms. FBL", 0, 1999, 2],
  ["Mia Chiu", "Ms. FBL", 0, 1999, 4],
  ["Michael Chen", "Public Speaking", 0, 1999, 2],
  ["Jennifer Lui", "Word Processing", 0, 1999, 1],
  ["Krystine Ongbongan", "Word Processing", 0, 1999, 6],
  ["Archanna Ravichandran", "$1000 Scholarship", 1, 1998, -2],
  ["An-Swol Hu", "Accounting I", 1, 1998, 2],
  ["Craig Larson", "Accounting I", 1, 1998, 10],
  ["Grace Park", "Accounting I", 1, 1998, 7],
  ["Mariann Hu", "Accounting I", 1, 1998, 8],
  ["Victoria Wang", "Accounting I", 1, 1998, 5],
  ["Lee Pang", "Accounting II", 1, 1998, 4],
  ["Michael Chang", "Accounting II", 1, 1998, 3],
  ["Michael Chen", "American Enterprise", 1, 1998, 4],
  ["Lee Pang", "Business Calculations", 1, 1998, 3],
  ["Michael Chang", "Business Calculations", 1, 1998, 5],
  ["Aileen Chan", "Business Law", 1, 1998, 7],
  ["Beth Landes", "Business Law", 1, 1998, 8],
  ["Jennifer Yen", "Business Law", 1, 1998, 3],
  ["Quynhvi Nguyen", "Business Law", 1, 1998, 5],
  ["Tik Yip", "Doug Kim", "Business Plan", 1, 1998, 4],
  ["Aileen Chan", "Business Procedures", 1, 1998, 10],
  ["Archanna Ravichandran", "Chapter Contribution Award", 1, 1998, 2],
  ["Jenny Liu", "FBLA Principles and Procedures", 1, 1998, 8],
  ["Mia Chiu", "FBLA Principles and Procedures", 1, 1998, 2],
  ["Michael Chen", "Impromptu Speaking", 1, 1998, 4],
  ["Henry Yei", "Information Processing Concepts", 1, 1998, 2],
  ["Jennifer Chao", "Introduction to Business", 1, 1998, 5],
  ["Jonathan Chong", "Introduction to Business", 1, 1998, 4],
  ["Nora Go", "Introduction to Business Communication", 1, 1998, 2],
  ["Roger Yei", "Introduction to Parliamentary Procedure", 1, 1998, 10],
  ["Ted Kim", "Job Description Manual", 1, 1998, 2],
  ["May Tseng", "Job Interview", 1, 1998, 6],
  ["Tik Yip", "Keyboarding Applications", 1, 1998, 6],
  ["Jennifer Lui", "Local Chapter Annual Business Report", 1, 1998, 8],
  ["Garrett Kuramoto", "Mr. FBL", 1, 1998, 3],
  ["Archanna Ravichandran", "Ms. FBL", 1, 1998, 5],
  ["Jeff Lo", "May Tseng", "Ted Kim", "Partnership with Business", 1, 1998, 5],
  ["Homestead", "Sweepstakes", 1, 1998, 2],
  ["An-Swol Hu", "Accounting I", 0, 1998, 1],
  ["Craig Larson", "Accounting I", 0, 1998, 5],
  ["Grace Park", "Accounting I", 0, 1998, 2],
  ["Mariann Hu", "Accounting I", 0, 1998, 3],
  ["Michael Wong", "Accounting I", 0, 1998, 6],
  ["Victoria Wang", "Accounting I", 0, 1998, 4],
  ["Amir Bakshaie", "Accounting II", 0, 1998, 9],
  ["Stephen Cheung", "Accounting II", 0, 1998, 5],
  ["Ben Wong", "Accounting II", 0, 1998, 4],
  ["Cindy Kodani", "Accounting II", 0, 1998, 6],
  ["Lee Pang", "Accounting II", 0, 1998, 1],
  ["Michael Chang", "Accounting II", 0, 1998, 2],
  ["Tracy Lu", "Accounting I", 2, 1996, 6],
  ["Ben Wong", "Business Calculations", 0, 1998, 9],
  ["Gautam Mehta", "Business Calculations", 0, 1998, 10],
  ["Lee Pang", "Business Calculations", 0, 1998, 3],
  ["Michael Chang", "Business Calculations", 0, 1998, 2],
  ["Garrett Kuramoto", "Business Communication", 0, 1998, 5],
  ["Marni Landes", "Business Communication", 0, 1998, 1],
  ["Nora Go", "Business Communication", 0, 1998, 8],
  ["Aileen Chan", "Business Law", 0, 1998, 3],
  ["Beth Landes", "Business Law", 0, 1998, 4],
  ["Jennifer Yen", "Business Law", 0, 1998, 1],
  ["Mia Chiu", "Business Law", 0, 1998, 6],
  ["Patty Chung", "Business Law", 0, 1998, 7],
  ["Quynhvi Nguyen", "Business Law", 0, 1998, 2],
  ["Jennifer Yen", "Business Math", 0, 1998, 9],
  ["Jenny Liu", "Business Math", 0, 1998, 10],
  ["Michael Wong", "Business Math", 0, 1998, 4],
  ["Steve Chae", "Business Math", 0, 1998, 6],
  ["Wayne Chang", "Business Math", 0, 1998, 7],
  ["Aileen Chan", "Business Procedures", 0, 1998, 4],
  ["Edward Hsu", "Business Procedures", 0, 1998, 5],
  ["James Dellinger", "Business Procedures", 0, 1998, 3],
  ["Jeff Lo", "Business Procedures", 0, 1998, 6],
  ["Mariann Hu", "Business Procedures", 0, 1998, 10],
  ["Cindy Kodani", "Computer Applications", 0, 1998, 5],
  ["David Huang", "Computer Applications", 0, 1998, 2],
  ["Richard Cheng", "Computer Applications", 0, 1998, 6],
  ["Bob Huang", "Computer Concepts", 0, 1998, 8],
  ["George Zhang", "Computer Concepts", 0, 1998, 10],
  ["Henry Yei", "Computer Concepts", 0, 1998, 5],
  ["Craig Larson", "Creed", 0, 1998, 4],
  ["Bob Huang", "Economics", 0, 1998, 7],
  ["Mary Tseng", "Economics", 0, 1998, 10],
  ["Roland Wong", "Economics", 0, 1998, 8],
  ["Steve Kuo", "Economics", 0, 1998, 9],
  [
    "Jenny Kim",
    "Rahul Mehta",
    "Kristine Trinh",
    "Entrepreneurship",
    0,
    1998,
    5,
  ],
  ["David Huang", "Information Processing Concepts", 0, 1998, 10],
  ["Henry Yei", "Information Processing Concepts", 0, 1998, 6],
  ["Jenny Liu", "Information Processing Concepts", 0, 1998, 7],
  ["Jennifer Chao", "Introduction to Business", 0, 1998, 5],
  ["Jonathan Chong", "Introduction to Business", 0, 1998, 2],
  ["May Tseng", "Job Interview", 0, 1998, 1],
  ["Tik Yip", "Keyboarding Applications", 0, 1998, 3],
  ["An-Swol Hu", "Mr. FBL", 0, 1998, 4],
  ["Garrett Kuramoto", "Mr. FBL", 0, 1998, 1],
  ["Archanna Ravichandran", "Ms. FBL", 0, 1998, 2],
  ["Grace Park", "Ms. FBL", 0, 1998, 3],
  ["Archanna Ravichandran", "Public Speaking", 0, 1998, 1],
  ["Jennifer Lui", "Word Processing", 0, 1998, 3],
  ["Michael Chang", "Accounting I", 1, 1997, 3],
  ["Lee Pang", "Accounting II", 1, 1997, 4],
  ["Tracy Lu", "Accounting II", 1, 1997, 7],
  ["Homestead", "American Enterprise", 1, 1997, 4],
  ["Michael Chang", "Business Calculations", 1, 1997, 6],
  ["Aileen Chan", "Business Law", 1, 1997, 6],
  ["Grace Park", "Business Law", 1, 1997, 2],
  ["Pang Lee", "Business Math", 1, 1997, 1],
  ["Cindy Kodani", "FBLA Principles and Procedures", 1, 1997, 7],
  ["Garrett Kuramoto", "FBLA Principles and Procedures", 1, 1997, 3],
  ["Michael Chen", "Impromptu Speaking", 1, 1997, 1],
  ["David Huang", "Information Processing Concepts", 1, 1997, 4],
  ["Mariann Hu", "Introduction to Business", 1, 1997, 6],
  ["Mia Chiu", "Introduction to Business", 1, 1997, 10],
  ["Garrett Kuramoto", "Introduction to Business Communication", 1, 1997, 6],
  ["Ted Kim", "Job Description Manual", 1, 1997, 4],
  ["Vivian Park", "Job Interview", 1, 1997, 6],
  ["Jennifer Lui", "Machine Transcription", 1, 1997, 10],
  ["Archanna Ravichandran", "Public Speaking", 1, 1997, 5],
  ["Homestead", "Sweepstakes", 1, 1997, 4],
  ["Ben Wong", "Accounting I", 0, 1997, 4],
  ["Michael Chang", "Accounting I", 0, 1997, 2],
  ["Stephen Cheung", "Accounting I", 0, 1997, 3],
  ["Lee Pang", "Accounting II", 0, 1997, 1],
  ["Tracy Lu", "Accounting II", 0, 1997, 2],
  ["Michael Chang", "Business Calculations", 0, 1997, 2],
  ["Aileen Chan", "Business Law", 0, 1997, 3],
  ["Grace Park", "Business Law", 0, 1997, 2],
  ["Lee Pang", "Business Math", 0, 1997, 1],
  ["Henry Yei", "Computer Concepts", 0, 1997, 5],
  ["Vinh Luu", "Computer Concepts", 0, 1997, 2],
  ["Craig Larson", "Creed", 0, 1997, 3],
  ["Brian Larson", "Vivian Wang", "Hank Wu", "Entrepreneurship", 0, 1997, 4],
  ["David Huang", "Information Processing Concepts", 0, 1997, 4],
  ["Mariann Hu", "Introduction to Business", 0, 1997, 1],
  ["Mia Chiu", "Introduction to Business", 0, 1997, 5],
  ["Vivian Park", "Job Interview", 0, 1997, 2],
  ["Tik Yip", "Keyboarding Applications", 0, 1997, 1],
  ["Garrett Kuramoto", "Mr. FBL", 0, 1997, 5],
  ["Tracy Lu", "Mrs. FBL", 0, 1997, 4],
  ["Archanna Ravichandran", "Public Speaking", 0, 1997, 3],
  ["Jennifer Lui", "Speed Typing", 0, 1997, 3],
  ["Tina Wang", "Word Processing", 0, 1997, 4],
  ["Hank Wu", "Accounting I", 1, 1996, 5],
  ["Lee-Yee Pang", "Accounting I", 1, 1996, 3],
  ["Tracy Lu", "Accounting I", 1, 1996, 2],
  ["Stephanie Ngan", "Business Law", 1, 1996, 4],
  ["Loc Tran", "Computer Applications", 1, 1996, 4],
  ["Harvey Vrsalovic", "Computer Concepts", 1, 1996, 3],
  ["Archanna Ravichandran", "Creed", 1, 1996, 4],
  ["Garrett Kuramoto", "Introduction to Business Communication", 1, 1996, 5],
  ["Bernie Su", "Job Description Manual", 1, 1996, 2],
  ["Homestead", "Sweepstakes", 1, 1996, 7],
  ["Hank Wu", "Accounting I", 0, 1996, 2],
  ["Lee-Yee Pang", "Accounting I", 0, 1996, 3],
  ["Tracy Lu", "Accounting I", 0, 1996, 1],
  ["Jessica Wong", "Accounting II", 0, 1996, 4],
  ["Stephanie Ngan", "Business Communication", 0, 1996, 2],
  ["Gabriel Tang", "Business Law", 0, 1996, 3],
  ["Stephanie Ngan", "Business Law", 0, 1996, 1],
  ["Michael Chang", "Business Math", 0, 1996, 4],
  ["James Dellinger", "Business Procedures", 0, 1996, 4],
  ["Mark Lee", "Business Procedures", 0, 1996, 2],
  ["Loc Tran", "Computer Applications", 0, 1996, 3],
  ["Harvey Vrsalovic", "Computer Concepts", 0, 1996, 4],
  ["Archanna Ravichandran", "Creed", 0, 1996, 2],
  ["Asof Shor", "Economics", 0, 1996, 2],
  ["Tran Luu", "Brian Larson", "Jason Ting", "Entrepreneurship", 0, 1996, 4],
  ["Sameh Kamel", "Introduction to Business", 0, 1996, 5],
  ["Vivian Park", "Job Interview", 0, 1996, 2],
  ["Jennifer Lui", "Keyboarding Applications", 0, 1996, 2],
  ["Tik Yip", "Keyboarding Applications", 0, 1996, 5],
  ["Bernie Su", "Mr. FBL", 0, 1996, 4],
  ["Nina Snipes", "Brian Larson", "Tina Wang", "Name Tag", 0, 1996, 1],
  ["Ken Chen", "Public Speaking", 0, 1996, 4],
  ["Hank Wu", "Speed Typing", 0, 1996, 1],
  ["An-Swol Hu", "Word Processing", 0, 1996, 2],
  ["Sean Nguyen", "Business Law", 2, 1995, 8],
  ["Brian Sanders", "Accounting II", 1, 1995, 1],
  ["SuShien Pang", "Business Calculations", 1, 1995, 4],
  ["Sean Nguyen", "Business Law", 1, 1995, 2],
  ["Tracy Lu", "Business Law", 1, 1995, 1],
  ["Sean Nguyen", "Business Procedures", 1, 1995, 3],
  [
    "Brian Larson",
    "Audrey Chan",
    "Brian Sanders",
    "Entrepreneurship",
    1,
    1995,
    5,
  ],
  ["Steve Hu", "Information Processing Concepts", 1, 1995, 4],
  ["Bernie Su", "Job Description Manual", 1, 1995, 3],
  ["Rita Chen", "Public Speaking", 1, 1995, 2],
  ["Homestead", "Sweepstakes", 1, 1995, 4],
  ["Waleed Kamel", "Accounting I", 0, 1995, 5],
  ["Brian Sanders", "Accounting II", 0, 1995, 1],
  ["Jessica Wong", "Accounting II", 0, 1995, 3],
  [
    "Bernie Su",
    "Jerome Fernando",
    "Asof Shor",
    "Battle of the Chapters",
    0,
    1995,
    3,
  ],
  ["Sean Nguyen", "Business Law", 0, 1995, 1],
  ["Stephanie Ngan", "Business Law", 0, 1995, 5],
  ["Tracy Lu", "Business Law", 0, 1995, 2],
  ["Sean Nguyen", "Business Procedures", 0, 1995, 4],
  ["Loc Tran", "Computer Applications", 0, 1995, 1],
  ["Kevin Kan", "Computer Concepts", 0, 1995, 5],
  ["SuShien Pang", "Economics", 0, 1995, 4],
  [
    "Brian Sanders",
    "Audrey Chan",
    "Brian Larson",
    "Entrepreneurship",
    0,
    1995,
    3,
  ],
  ["Steve Hu", "Information Processing Concepts", 0, 1995, 4],
  ["Vivian Park", "Job Interview", 0, 1995, 4],
  ["Asof Shor", "Keyboarding Applications", 0, 1995, 5],
  ["Rita Chen", "Public Speaking", 0, 1995, 2],
  ["Zhuanjia Gu", "Speed Typing", 0, 1995, 3],
  ["Brian Sanders", "Accounting I", 0, 1994, 5],
  ["Brian Sanders", "Accounting II", 0, 1994, 1],
  ["Mimi Hayakawa", "Accounting II", 0, 1994, 4],
  ["SuShien Pang", "Business Calculations", 0, 1994, 4],
  ["Sean Nguyen", "Business Law", 0, 1994, 1],
  ["Waleed Kamel", "Business Law", 0, 1994, 5],
  ["Sean Nguyen", "Business Procedures", 0, 1994, 4],
  ["Darius Jazayeri", "Computer Concepts", 0, 1994, 5],
  ["Rita Chen", "Public Speaking", 0, 1994, 3],
  [
    "Michael Huang",
    "Michael Lee",
    "Sabah Khan",
    "Tasha Matharu",
    "Parliamentary Procedure",
    0,
    2001,
    2,
  ],
  [
    "Steve Chae",
    "Sabah Khan",
    "Tasha Matharu",
    "Roger Yei",
    "Parliamentary Procedure",
    1,
    2000,
    5,
  ],
  [
    "Roger Yei",
    "Steve Chae",
    "Sabah Khan",
    "Tasha Matharu",
    "Parliamentary Procedure",
    0,
    2000,
    2,
  ],
  [
    "Roger Yei",
    "Steve Chae",
    "Richard Cheng",
    "Tasha Matharu",
    "Parliamentary Procedure",
    1,
    1999,
    4,
  ],
  [
    "Roger Yei",
    "Steve Chae",
    "Richard Cheng",
    "Brian Daner",
    "Tasha Matharu",
    "Parliamentary Procedure",
    0,
    1999,
    2,
  ],
  [
    "Jason Ting",
    "John Chiang",
    "Stephen Westhafer",
    "Roger Yei",
    "Tik Yip",
    "Parliamentary Procedure",
    0,
    1998,
    5,
  ],
  [
    "Jason Ting",
    "Henry Yei",
    "An-Swol Hu",
    "Andy Chen",
    "John Chiang",
    "Parliamentary Procedure",
    0,
    1997,
    3,
  ],
  [
    "Ben Tao",
    "Jeremy Friedenthal",
    "Ken Chen",
    "Zhuanjia Gu",
    "Michael Chen",
    "Parliamentary Procedure",
    0,
    1996,
    3,
  ],
  [
    "Ben Tao",
    "Jeremy Friedenthal",
    "Ken Chen",
    "Spencer Pang",
    "Waleed Kamel",
    "Parliamentary Procedure",
    0,
    1995,
    2,
  ],
  [
    "Emerald Chun",
    "Ritu Kiragi",
    "Matt Lee",
    "Sangeeta Monda",
    "Stephanie Zau",
    "Parliamentary Procedure",
    1,
    2008,
    4,
  ],
  [
    "Stephanie Zau",
    "Emerald Chun",
    "Ritu Kuragi",
    "Sangeeta Mondal",
    "Matthew Lee",
    "Parliamentary Procedure",
    0,
    2008,
    3,
  ],
  [
    "Alex Shiroglazov",
    "Emerald Chun",
    "Justin Chou",
    "Krzys Brozek",
    "Stephanie Zau",
    "Parliamentary Procedure",
    1,
    2007,
    5,
  ],
  [
    "Krzys Brozek",
    "Emerald Chun",
    "Justin Chou",
    "Alex Shiroglazov",
    "Stephanie Zau",
    "Parliamentary Procedure",
    0,
    2007,
    3,
  ],
  [
    "Oishee Bose",
    "Niranjan Manoharan",
    "Alex Shiroglazov",
    "Aditya Bandi",
    "Parliamentary Procedure",
    0,
    2006,
    3,
  ],
  [
    "Tasha Matharu",
    "Michael Huang",
    "Michael Lee",
    "Sabah Khan",
    "Parliamentary Procedure",
    1,
    2001,
    5,
  ],
];

export default class UpdateBefore08 extends React.Component {
  constructor(props) {
    super(props);
    this.updateDB = this.updateDB.bind(this);
  }

  updateDB() {
    var db = firebase.firestore();
    //max length = 8
    //num people is 5-(8-length)

    for (let i = 0; i < results.length; i++) {
      let entry = results[i];
      let numPeople = 5 - (9 - entry.length);
      let people = [];
      let event = entry[numPeople];
      let conf = entry[numPeople + 1];
      let year = entry[numPeople + 2];
      let place = entry[numPeople + 3];
      if (conf == 0) {
        conf = "Bay";
      } else if (conf == 1) {
        conf = "State";
      } else {
        conf = "Nationals";
      }
      for (let k = 0; k < numPeople; k++) {
        people.push(entry[k]);
      }
      for (let k = 0; k < numPeople; k++) {
        db.collection("eventsQuery")
          .doc(event)
          .collection(String(year))
          .doc(conf)
          .set(
            {
              [people[k]]: place,
            },
            { merge: true }
          )
          .then(function () {
            console.log("Document successfully written!");
          })
          .catch(function (error) {
            console.error("Error writing document: ", error);
          });
      }
    }
  }

  render() {
    return <Button onClick={this.updateDB}>Update 'fore 08</Button>;
  }
}
